<?php

namespace s9e\TextFormatter\Tests\ConfigBuilder;

use s9e\TextFormatter\Tests\Test,
    s9e\TextFormatter\ConfigBuilder\Tag,
    s9e\TextFormatter\ConfigBuilder\TemplateChecker;

include_once __DIR__ . '/../../src/autoloader.php';

/**
* @covers s9e\TextFormatter\ConfigBuilder\TemplateChecker
*/
class TemplateCheckerTest extends Test
{
	/**
	* @testdox checkUnsafe() throws an exception on invalid XML
	* @expectedException InvalidArgumentException
	* @expectedExceptionMessage Invalid XML in template: Premature end of data in tag template
	*/
	public function testUnsafeInvalidXML()
	{
		TemplateChecker::checkUnsafe('<x>', new Tag);
	}

	// Start of content generated by ../scripts/patchTemplateCheckerTest.php
	/**
	* @testdox checkUnsafe() identifies <script src="{@url}"/> as unsafe
	*/
	public function testCheckUnsafeA269924E()
	{
		$this->testUnsafeTags(
			'<script src="{@url}"/>',
			"The template contains a 'script' element with a non-fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <SCRIPT src="{@url}"/> as unsafe
	*/
	public function testCheckUnsafeECFD591A()
	{
		$this->testUnsafeTags(
			'<SCRIPT src="{@url}"/>',
			"The template contains a 'SCRIPT' element with a non-fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script SRC="{@url}"/> as unsafe
	*/
	public function testCheckUnsafe677FB29A()
	{
		$this->testUnsafeTags(
			'<script SRC="{@url}"/>',
			"The template contains a 'script' element with a non-fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></script> as unsafe
	*/
	public function testCheckUnsafeAFAF8AE6()
	{
		$this->testUnsafeTags(
			'<script><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></script>',
			"The template contains a 'script' element with a dynamically generated 'src' attribute that does not use a fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></script> as unsafe
	*/
	public function testCheckUnsafe2B68C5D8()
	{
		$this->testUnsafeTags(
			'<script><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></script>',
			"The template contains a 'script' element with a dynamically generated 'SRC' attribute that does not use a fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:element name="script"><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></xsl:element> as unsafe
	*/
	public function testCheckUnsafeE3DAC5EC()
	{
		$this->testUnsafeTags(
			'<xsl:element name="script"><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></xsl:element>',
			"The template contains a dynamically generated 'script' element with a dynamically generated 'src' attribute that does not use a fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:element name="SCRIPT"><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></xsl:element> as unsafe
	*/
	public function testCheckUnsafe5FB05B22()
	{
		$this->testUnsafeTags(
			'<xsl:element name="SCRIPT"><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></xsl:element>',
			"The template contains a dynamically generated 'SCRIPT' element with a dynamically generated 'SRC' attribute that does not use a fixed URL"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <b><xsl:copy-of select="@onclick"/></b> as unsafe
	*/
	public function testCheckUnsafe88ADF3EE()
	{
		$this->testUnsafeTags(
			'<b><xsl:copy-of select="@onclick"/></b>',
			"Undefined attribute 'onclick'"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <b><xsl:copy-of select=" @ onclick "/></b> as unsafe
	*/
	public function testCheckUnsafe1910BA7D()
	{
		$this->testUnsafeTags(
			'<b><xsl:copy-of select=" @ onclick "/></b>',
			"Undefined attribute 'onclick'"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <b><xsl:copy-of select="@title"/></b> as safe
	*/
	public function testCheckUnsafe990F4294()
	{
		$this->testUnsafeTags(
			'<b><xsl:copy-of select="@title"/></b>'
		);
	}

	/**
	* @testdox checkUnsafe() identifies <b><xsl:copy-of select=" @ title "/></b> as safe
	*/
	public function testCheckUnsafe358E72E5()
	{
		$this->testUnsafeTags(
			'<b><xsl:copy-of select=" @ title "/></b>'
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:copy-of select="script"/> as unsafe
	*/
	public function testCheckUnsafeEFC1AC5D()
	{
		$this->testUnsafeTags(
			'<xsl:copy-of select="script"/>',
			"Cannot assess 'xsl:copy-of' select expression 'script' to be safe"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:copy-of select=" script "/> as unsafe
	*/
	public function testCheckUnsafeD2943232()
	{
		$this->testUnsafeTags(
			'<xsl:copy-of select=" script "/>',
			"Cannot assess 'xsl:copy-of' select expression 'script' to be safe"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:copy-of select="parent::*"/> as unsafe
	*/
	public function testCheckUnsafe14D8856E()
	{
		$this->testUnsafeTags(
			'<xsl:copy-of select="parent::*"/>',
			"Cannot assess 'xsl:copy-of' select expression 'parent::*' to be safe"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:element name="script"><xsl:apply-templates/></xsl:element> as unsafe
	*/
	public function testCheckUnsafeF1561B5E()
	{
		$this->testUnsafeTags(
			'<xsl:element name="script"><xsl:apply-templates/></xsl:element>',
			"A dynamically generated 'script' element lets unfiltered data through"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:element name="SCRIPT"><xsl:apply-templates/></xsl:element> as unsafe
	*/
	public function testCheckUnsafe7A40C9A2()
	{
		$this->testUnsafeTags(
			'<xsl:element name="SCRIPT"><xsl:apply-templates/></xsl:element>',
			"A dynamically generated 'SCRIPT' element lets unfiltered data through"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:apply-templates/></script> as unsafe
	*/
	public function testCheckUnsafe9D85E8A7()
	{
		$this->testUnsafeTags(
			'<script><xsl:apply-templates/></script>',
			"A 'script' element lets unfiltered data through"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <SCRIPT><xsl:apply-templates/></SCRIPT> as unsafe
	*/
	public function testCheckUnsafeD6088721()
	{
		$this->testUnsafeTags(
			'<SCRIPT><xsl:apply-templates/></SCRIPT>',
			"A 'SCRIPT' element lets unfiltered data through"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script src="http://localhost/{@foo}"/> as unsafe
	*/
	public function testCheckUnsafe4C46C90C()
	{
		$this->testUnsafeTags(
			'<script src="http://localhost/{@foo}"/>',
			"Undefined attribute 'foo'"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <SCRIPT src="http://localhost/{@foo}"/> as unsafe
	*/
	public function testCheckUnsafe4DE9B1E3()
	{
		$this->testUnsafeTags(
			'<SCRIPT src="http://localhost/{@foo}"/>',
			"Undefined attribute 'foo'"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as unsafe
	*/
	public function testCheckUnsafe26F4CFED()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			"Undefined attribute 'foo'"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as unsafe if attribute 'foo' has filter '#raw'
	*/
	public function testCheckUnsafe829FC30F()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			"Attribute 'foo' is not properly filtered to be used in JS",
			array('attributes' => array('foo' => array('filterChain' => array('#raw'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#url'
	*/
	public function testCheckUnsafeE68352A8()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#url'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#int'
	*/
	public function testCheckUnsafe3EBBA835()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#int'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#float'
	*/
	public function testCheckUnsafeE6E82972()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#float'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#range'
	*/
	public function testCheckUnsafe0EAB91F7()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#range'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#number'
	*/
	public function testCheckUnsafe78CE422C()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#number'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <script><xsl:value-of select="@foo"/></script> as safe if attribute 'foo' has filter '#simpletext'
	*/
	public function testCheckUnsafeD70D4F35()
	{
		$this->testUnsafeTags(
			'<script><xsl:value-of select="@foo"/></script>',
			NULL,
			array('attributes' => array('foo' => array('filterChain' => array('#simpletext'))))
		);
	}

	/**
	* @testdox checkUnsafe() identifies <xsl:element name="style"><xsl:apply-templates/></xsl:element> as unsafe
	*/
	public function testCheckUnsafe6E35D9A1()
	{
		$this->testUnsafeTags(
			'<xsl:element name="style"><xsl:apply-templates/></xsl:element>',
			"A dynamically generated 'style' element lets unfiltered data through"
		);
	}

	/**
	* @testdox checkUnsafe() identifies <style><xsl:apply-templates/></style> as unsafe
	*/
	public function testCheckUnsafe0E136F67()
	{
		$this->testUnsafeTags(
			'<style><xsl:apply-templates/></style>',
			"A 'style' element lets unfiltered data through"
		);
	}
	// End of content generated by ../scripts/patchTemplateCheckerTest.php

	/**
	* @group dataProvider
	* @dataProvider getUnsafeTags
	*/
	public function testUnsafeTags($template, $exceptionMsg = null, array $tagOptions = array())
	{
		if (1&&isset($exceptionMsg))
		{
			$this->setExpectedException(
				's9e\\TextFormatter\\ConfigBuilder\\UnsafeTemplateException',
				$exceptionMsg
			);
		}

		TemplateChecker::checkUnsafe(
			$template,
			new Tag($tagOptions)
		);
	}

	public function getUnsafeTags()
	{
		return array(
			array(
				'<script src="{@url}"/>',
				"The template contains a 'script' element with a non-fixed URL"
			),
			array(
				'<SCRIPT src="{@url}"/>',
				"The template contains a 'SCRIPT' element with a non-fixed URL"
			),
			array(
				'<script SRC="{@url}"/>',
				"The template contains a 'script' element with a non-fixed URL"
			),
			array(
				'<script><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></script>',
				"The template contains a 'script' element with a dynamically generated 'src' attribute that does not use a fixed URL"
			),
			array(
				'<script><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></script>',
				"The template contains a 'script' element with a dynamically generated 'SRC' attribute that does not use a fixed URL"
			),
			array(
				'<xsl:element name="script"><xsl:attribute name="src"><xsl:value-of select="@url"/></xsl:attribute></xsl:element>',
				"The template contains a dynamically generated 'script' element with a dynamically generated 'src' attribute that does not use a fixed URL"
			),
			array(
				'<xsl:element name="SCRIPT"><xsl:attribute name="SRC"><xsl:value-of select="@url"/></xsl:attribute></xsl:element>',
				"The template contains a dynamically generated 'SCRIPT' element with a dynamically generated 'SRC' attribute that does not use a fixed URL"
			),
			array(
				'<b><xsl:copy-of select="@onclick"/></b>',
				"Undefined attribute 'onclick'"
			),
			array(
				'<b><xsl:copy-of select=" @ onclick "/></b>',
				"Undefined attribute 'onclick'"
			),
			array(
				'<b><xsl:copy-of select="@title"/></b>'
			),
			array(
				'<b><xsl:copy-of select=" @ title "/></b>'
			),
			array(
				'<xsl:copy-of select="script"/>',
				"Cannot assess 'xsl:copy-of' select expression 'script' to be safe"
			),
			array(
				'<xsl:copy-of select=" script "/>',
				"Cannot assess 'xsl:copy-of' select expression 'script' to be safe"
			),
			array(
				'<xsl:copy-of select="parent::*"/>',
				"Cannot assess 'xsl:copy-of' select expression 'parent::*' to be safe"
			),
			array(
				'<xsl:element name="script"><xsl:apply-templates/></xsl:element>',
				"A dynamically generated 'script' element lets unfiltered data through"
			),
			array(
				'<xsl:element name="SCRIPT"><xsl:apply-templates/></xsl:element>',
				"A dynamically generated 'SCRIPT' element lets unfiltered data through"
			),
			array(
				'<script><xsl:apply-templates/></script>',
				"A 'script' element lets unfiltered data through"
			),
			array(
				'<SCRIPT><xsl:apply-templates/></SCRIPT>',
				"A 'SCRIPT' element lets unfiltered data through"
			),
			array(
				'<script src="http://localhost/{@foo}"/>',
				"Undefined attribute 'foo'"
			),
			array(
				'<SCRIPT src="http://localhost/{@foo}"/>',
				"Undefined attribute 'foo'"
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				"Undefined attribute 'foo'"
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				"Attribute 'foo' is not properly filtered to be used in JS",
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#raw')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				'<script><xsl:value-of select="@foo"/></script>',
				null,
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#simpletext')
						)
					)
				)
			),
			array(
				'<xsl:element name="style"><xsl:apply-templates/></xsl:element>',
				"A dynamically generated 'style' element lets unfiltered data through"
			),
			array(
				'<style><xsl:apply-templates/></style>',
				"A 'style' element lets unfiltered data through"
			),
/**
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a <style> tag',
				'<style><xsl:value-of select="@foo"/></style>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a <style> tag',
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#raw')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#uint')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#color')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				false,
				'<style><xsl:value-of select="@foo"/></style>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#simpletext')
						)
					)
				)
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a 'style' attribute",
				'<b style="color:{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a 'style' attribute",
				'<b STYLE="color:{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a 'style' attribute",
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#raw')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#uint')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#color')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				false,
				'<b style="color:{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#simpletext')
						)
					)
				)
			),
			array(
				"The template contains a dynamically generated 'style' attribute that lets unfiltered data through",
				'<b><xsl:attribute name="style"><xsl:apply-templates/></xsl:attribute></b>'
			),
			array(
				"The template contains a dynamically generated 'style' attribute that lets unfiltered data through",
				'<b><xsl:attribute name="STYLE"><xsl:apply-templates/></xsl:attribute></b>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a dynamically generated 'style' attribute",
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a dynamically generated 'style' attribute",
				'<b><xsl:attribute name="STYLE"><xsl:value-of select="@foo"/></xsl:attribute></b>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes inside of a dynamically generated 'style' attribute",
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#raw')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#uint')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#color')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				false,
				'<b><xsl:attribute name="style"><xsl:value-of select="@foo"/></xsl:attribute></b>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#simpletext')
						)
					)
				)
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<a href="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<a HREF="{@foo}"/>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a dynamically generated attribute that expects a valid URL',
				'<a><xsl:attribute name="href"><xsl:value-of select="@foo"/></xsl:attribute></a>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a dynamically generated attribute that expects a valid URL',
				'<a><xsl:attribute name="HREF"><xsl:value-of select="@foo"/></xsl:attribute></a>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<form action="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<q cite="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<object data="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<button formaction="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<html manifest="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<video poster="{@foo}"/>'
			),
			array(
				"The template uses unfiltered or improperly filtered attributes where a valid URL is expected",
				'<img src="{@foo}"/>'
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('urlencode')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('rawurlencode')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#id')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#uint')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				'The template uses unfiltered or improperly filtered attributes where a valid URL is expected',
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#regexp'),
							'regexp'      => '#[0-9]+#'
						)
					)
				)
			),
			array(
				false,
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#regexp'),
							'regexp'      => '#^[0-9]+$#'
						)
					)
				)
			),
			array(
				'The template uses unfiltered or improperly filtered attributes where a valid URL is expected',
				'<a href="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#regexp'),
							'regexp'      => '#^[a-z]+:[a-z]+$#'
						)
					)
				)
			),
			array(
				'The template contains a dynamically generated attribute that expects a valid URL but lets unfiltered data through',
				'<a><xsl:attribute name="href"><xsl:apply-templates/></xsl:attribute></a>'
			),
			array(
				'The template contains a dynamically generated attribute that expects a valid URL but lets unfiltered data through',
				'<a><xsl:attribute name="HREF"><xsl:apply-templates/></xsl:attribute></a>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of an HTML event attribute',
				'<b onclick="{@foo}"/>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of an HTML event attribute',
				'<b ONCLICK="{@foo}"/>'
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#url')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#int')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#uint')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#float')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#range')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#number')
						)
					)
				)
			),
			array(
				false,
				'<b onclick="{@foo}"/>',
				array(
					'attributes' => array(
						'foo' => array(
							'filterChain' => array('#simpletext')
						)
					)
				)
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a dynamically created HTML event attribute',
				'<b><xsl:attribute name="onclick"><xsl:value-of select="@foo"/></xsl:attribute></b>'
			),
			array(
				'The template uses unfiltered or improperly filtered attributes inside of a dynamically created HTML event attribute',
				'<b><xsl:attribute name="ONCLICK"><xsl:value-of select="@foo"/></xsl:attribute></b>'
			),
			array(
				'The template contains an HTML event attribute that lets unfiltered data through',
				'<b><xsl:attribute name="onclick"><xsl:apply-templates/></xsl:attribute></b>'
			),
			array(
				'The template contains an HTML event attribute that lets unfiltered data through',
				'<b><xsl:attribute name="ONCLICK"><xsl:apply-templates/></xsl:attribute></b>'
			),
/**/
		);
	}
}