<?php

namespace s9e\TextFormatter\Tests\ConfigBuilder\Helpers;

use s9e\TextFormatter\Tests\Test;
use s9e\TextFormatter\ConfigBuilder\Helpers\RegexpHelper;

/**
* @covers s9e\TextFormatter\ConfigBuilder\Helpers\RegexpHelper
*/
class RegexpHelperTest extends Test
{
	// Start of content generated by ../../../scripts/patchRegexpHelperTest.php
	/**
	* @testdox buildRegexpFromList(['foo']) returns 'foo'
	*/
	public function test_buildRegexpFromList_2e6b327f()
	{
		$this->assertSame(
			'foo',
			RegexpHelper::buildRegexpFromList(array('foo'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'foo']) returns 'foo'
	*/
	public function test_buildRegexpFromList_efc21f10()
	{
		$this->assertSame(
			'foo',
			RegexpHelper::buildRegexpFromList(array('foo', 'foo'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['a']) returns 'a'
	*/
	public function test_buildRegexpFromList_37e7519f()
	{
		$this->assertSame(
			'a',
			RegexpHelper::buildRegexpFromList(array('a'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['a', 'a']) returns 'a'
	*/
	public function test_buildRegexpFromList_46ecdb38()
	{
		$this->assertSame(
			'a',
			RegexpHelper::buildRegexpFromList(array('a', 'a'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['apple', 'april']) returns 'ap(?:ple|ril)'
	*/
	public function test_buildRegexpFromList_8b59a499()
	{
		$this->assertSame(
			'ap(?:ple|ril)',
			RegexpHelper::buildRegexpFromList(array('apple', 'april'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['bar', 'baz']) returns 'ba[rz]'
	*/
	public function test_buildRegexpFromList_e7ffb86f()
	{
		$this->assertSame(
			'ba[rz]',
			RegexpHelper::buildRegexpFromList(array('bar', 'baz'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'fool']) returns 'fool?'
	*/
	public function test_buildRegexpFromList_1dff1ab5()
	{
		$this->assertSame(
			'fool?',
			RegexpHelper::buildRegexpFromList(array('foo', 'fool'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'axed']) returns 'ax(?:ed)?'
	*/
	public function test_buildRegexpFromList_b4f156be()
	{
		$this->assertSame(
			'ax(?:ed)?',
			RegexpHelper::buildRegexpFromList(array('ax', 'axed'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['a', '.'], ["specialChars" => ["." => "."]]) returns '.'
	*/
	public function test_buildRegexpFromList_c29ced5()
	{
		$this->assertSame(
			'.',
			RegexpHelper::buildRegexpFromList(
				array('a', '.'),
				array('specialChars' => array('.' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['hip', 'hop', 'h.p'], ["specialChars" => ["." => "."]]) returns 'h.p'
	*/
	public function test_buildRegexpFromList_6ab3a485()
	{
		$this->assertSame(
			'h.p',
			RegexpHelper::buildRegexpFromList(
				array('hip', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['hi', 'hop', 'h.p'], ["specialChars" => ["." => "."]]) returns 'h(?:i|.p)'
	*/
	public function test_buildRegexpFromList_8fc43cb0()
	{
		$this->assertSame(
			'h(?:i|.p)',
			RegexpHelper::buildRegexpFromList(
				array('hi', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['h', 'h.'], ["specialChars" => ["." => "."]]) returns 'h.?'
	*/
	public function test_buildRegexpFromList_9ba9174b()
	{
		$this->assertSame(
			'h.?',
			RegexpHelper::buildRegexpFromList(
				array('h', 'h.'),
				array('specialChars' => array('.' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['h.', 'hd'], ["specialChars" => ["." => ".", "d" => "\\d\\d"]]) returns 'h(?:.|\\d\\d)'
	*/
	public function test_buildRegexpFromList_a1628b44()
	{
		$this->assertSame(
			'h(?:.|\\d\\d)',
			RegexpHelper::buildRegexpFromList(
				array('h.', 'hd'),
				array('specialChars' => array('.' => '.', 'd' => '\\d\\d'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['hXXXXXXXXXXX', 'h\\^$.[]()+*?', 'hotel'], ["specialChars" => ["X" => "."]]) returns 'h(?:...........|otel)'
	*/
	public function test_buildRegexpFromList_71d6e963()
	{
		$this->assertSame(
			'h(?:...........|otel)',
			RegexpHelper::buildRegexpFromList(
				array('hXXXXXXXXXXX', 'h\\^$.[]()+*?', 'hotel'),
				array('specialChars' => array('X' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['zdDhHsSvVwW', 'z..........', 'zebra'], ["specialChars" => ["\\d" => "\\d", "\\D" => "\\D", "\\h" => "\\h", "\\H" => "\\H", "\\s" => "\\s", "\\S" => "\\S", "\\v" => "\\v", "\\V" => "\\V", "\\w" => "\\w", "\\W" => "\\W", "." => "."]]) returns 'z(?:..........|ebra)'
	*/
	public function test_buildRegexpFromList_f23831ca()
	{
		$this->assertSame(
			'z(?:..........|ebra)',
			RegexpHelper::buildRegexpFromList(
				array('zdDhHsSvVwW', 'z..........', 'zebra'),
				array('specialChars' => array('\\d' => '\\d', '\\D' => '\\D', '\\h' => '\\h', '\\H' => '\\H', '\\s' => '\\s', '\\S' => '\\S', '\\v' => '\\v', '\\V' => '\\V', '\\w' => '\\w', '\\W' => '\\W', '.' => '.'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['h$', 'h.'], ["specialChars" => ["." => ".", "$" => "$"]]) returns 'h(?:$|.)'
	*/
	public function test_buildRegexpFromList_34005f32()
	{
		$this->assertSame(
			'h(?:$|.)',
			RegexpHelper::buildRegexpFromList(
				array('h$', 'h.'),
				array('specialChars' => array('.' => '.', '$' => '$'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['!', '#', '$', '(', ')', '*', '+', '-', '.', ':', '<', '=', '>', '?', '[', '\\', ']', '^', '{', '|', '}']) returns '[-!:<=>\\#\\\\\\]}$()*+.?[{|^]'
	*/
	public function test_buildRegexpFromList_8cb33695()
	{
		$this->assertSame(
			'[-!:<=>\\#\\\\\\]}$()*+.?[{|^]',
			RegexpHelper::buildRegexpFromList(array('!', '#', '$', '(', ')', '*', '+', '-', '.', ':', '<', '=', '>', '?', '[', '\\', ']', '^', '{', '|', '}'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['xy', '^y'], ["specialChars" => ["^" => "^"]]) returns '(?:x|^)y'
	*/
	public function test_buildRegexpFromList_8a71e271()
	{
		$this->assertSame(
			'(?:x|^)y',
			RegexpHelper::buildRegexpFromList(
				array('xy', '^y'),
				array('specialChars' => array('^' => '^'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['xy', 'x$'], ["specialChars" => ["$" => "$"]]) returns 'x(?:y|$)'
	*/
	public function test_buildRegexpFromList_13ba1bfa()
	{
		$this->assertSame(
			'x(?:y|$)',
			RegexpHelper::buildRegexpFromList(
				array('xy', 'x$'),
				array('specialChars' => array('$' => '$'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'bar']) returns '(?:bar|foo)'
	*/
	public function test_buildRegexpFromList_a3302107()
	{
		$this->assertSame(
			'(?:bar|foo)',
			RegexpHelper::buildRegexpFromList(array('foo', 'bar'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['*foo', '\\bar'], ["useLookahead" => true]) returns '(?=[\\\\*])(?:\\*foo|\\\\bar)'
	*/
	public function test_buildRegexpFromList_8b9e42a9()
	{
		$this->assertSame(
			'(?=[\\\\*])(?:\\*foo|\\\\bar)',
			RegexpHelper::buildRegexpFromList(
				array('*foo', '\\bar'),
				array('useLookahead' => true)
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['?', 'bar'], ["specialChars" => ["?" => "."], "useLookahead" => true]) returns '(?:.|bar)'
	*/
	public function test_buildRegexpFromList_7ffb138d()
	{
		$this->assertSame(
			'(?:.|bar)',
			RegexpHelper::buildRegexpFromList(
				array('?', 'bar'),
				array('specialChars' => array('?' => '.'), 'useLookahead' => true)
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['a', 'b']) returns '[ab]'
	*/
	public function test_buildRegexpFromList_c90b2457()
	{
		$this->assertSame(
			'[ab]',
			RegexpHelper::buildRegexpFromList(array('a', 'b'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['♠', '♣', '♥', '♦']) returns '[♠♣♥♦]'
	*/
	public function test_buildRegexpFromList_6335367b()
	{
		$this->assertSame(
			'[♠♣♥♦]',
			RegexpHelper::buildRegexpFromList(array('♠', '♣', '♥', '♦'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['lock', 'sock']) returns '[ls]ock'
	*/
	public function test_buildRegexpFromList_a3cf0b4d()
	{
		$this->assertSame(
			'[ls]ock',
			RegexpHelper::buildRegexpFromList(array('lock', 'sock'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'afoo'], ["useLookahead" => true]) returns '(?=[af])a?foo'
	*/
	public function test_buildRegexpFromList_8613531b()
	{
		$this->assertSame(
			'(?=[af])a?foo',
			RegexpHelper::buildRegexpFromList(
				array('foo', 'afoo'),
				array('useLookahead' => true)
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['boast', 'boost']) returns 'bo[ao]st'
	*/
	public function test_buildRegexpFromList_4bbad47d()
	{
		$this->assertSame(
			'bo[ao]st',
			RegexpHelper::buildRegexpFromList(array('boast', 'boost'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['pest', 'pst']) returns 'pe?st'
	*/
	public function test_buildRegexpFromList_596d7420()
	{
		$this->assertSame(
			'pe?st',
			RegexpHelper::buildRegexpFromList(array('pest', 'pst'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['boast', 'boost', 'bost']) returns 'bo[ao]?st'
	*/
	public function test_buildRegexpFromList_e644dceb()
	{
		$this->assertSame(
			'bo[ao]?st',
			RegexpHelper::buildRegexpFromList(array('boast', 'boost', 'bost'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['boost', 'best']) returns 'b(?:e|oo)st'
	*/
	public function test_buildRegexpFromList_aeb9f217()
	{
		$this->assertSame(
			'b(?:e|oo)st',
			RegexpHelper::buildRegexpFromList(array('boost', 'best'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['boost', 'bst']) returns 'b(?:oo)?st'
	*/
	public function test_buildRegexpFromList_be3ccba2()
	{
		$this->assertSame(
			'b(?:oo)?st',
			RegexpHelper::buildRegexpFromList(array('boost', 'bst'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['best', 'boost', 'bust']) returns 'b(?:[eu]|oo)st'
	*/
	public function test_buildRegexpFromList_9753e32d()
	{
		$this->assertSame(
			'b(?:[eu]|oo)st',
			RegexpHelper::buildRegexpFromList(array('best', 'boost', 'bust'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['boost', 'bst', 'cool']) returns '(?:b(?:oo)?st|cool)'
	*/
	public function test_buildRegexpFromList_9a764069()
	{
		$this->assertSame(
			'(?:b(?:oo)?st|cool)',
			RegexpHelper::buildRegexpFromList(array('boost', 'bst', 'cool'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['boost', 'bst', 'cost']) returns '(?:b(?:oo)?|co)st'
	*/
	public function test_buildRegexpFromList_53994ab6()
	{
		$this->assertSame(
			'(?:b(?:oo)?|co)st',
			RegexpHelper::buildRegexpFromList(array('boost', 'bst', 'cost'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aax', 'aay', 'aax', 'aay']) returns 'aa[xy]'
	*/
	public function test_buildRegexpFromList_560c8444()
	{
		$this->assertSame(
			'aa[xy]',
			RegexpHelper::buildRegexpFromList(array('aax', 'aay', 'aax', 'aay'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aaax', 'aaay', 'baax', 'baay']) returns '[ab]aa[xy]'
	*/
	public function test_buildRegexpFromList_f3709bef()
	{
		$this->assertSame(
			'[ab]aa[xy]',
			RegexpHelper::buildRegexpFromList(array('aaax', 'aaay', 'baax', 'baay'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aaax', 'aaay', 'bbaax', 'bbaay']) returns '(?:a|bb)aa[xy]'
	*/
	public function test_buildRegexpFromList_7c889532()
	{
		$this->assertSame(
			'(?:a|bb)aa[xy]',
			RegexpHelper::buildRegexpFromList(array('aaax', 'aaay', 'bbaax', 'bbaay'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aaax', 'aaay', 'aax', 'aay']) returns 'aaa?[xy]'
	*/
	public function test_buildRegexpFromList_77f7fecb()
	{
		$this->assertSame(
			'aaa?[xy]',
			RegexpHelper::buildRegexpFromList(array('aaax', 'aaay', 'aax', 'aay'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['abx', 'aby', 'cdx', 'cdy']) returns '(?:ab|cd)[xy]'
	*/
	public function test_buildRegexpFromList_62e02b3a()
	{
		$this->assertSame(
			'(?:ab|cd)[xy]',
			RegexpHelper::buildRegexpFromList(array('abx', 'aby', 'cdx', 'cdy'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['axx', 'ayy', 'bbxx', 'bbyy']) returns '(?:a|bb)(?:xx|yy)'
	*/
	public function test_buildRegexpFromList_8a86c707()
	{
		$this->assertSame(
			'(?:a|bb)(?:xx|yy)',
			RegexpHelper::buildRegexpFromList(array('axx', 'ayy', 'bbxx', 'bbyy'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['axx', 'ayy', 'bbxx', 'bbyy', 'c']) returns '(?:c|(?:a|bb)(?:xx|yy))'
	*/
	public function test_buildRegexpFromList_59fb8e0()
	{
		$this->assertSame(
			'(?:c|(?:a|bb)(?:xx|yy))',
			RegexpHelper::buildRegexpFromList(array('axx', 'ayy', 'bbxx', 'bbyy', 'c'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['axx', 'ayy', 'azz', 'bbxx', 'bbyy', 'c']) returns '(?:c|a(?:xx|yy|zz)|bb(?:xx|yy))'
	*/
	public function test_buildRegexpFromList_ea302659()
	{
		$this->assertSame(
			'(?:c|a(?:xx|yy|zz)|bb(?:xx|yy))',
			RegexpHelper::buildRegexpFromList(array('axx', 'ayy', 'azz', 'bbxx', 'bbyy', 'c'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ac', 'af', 'bbc', 'bbf', 'c']) returns '(?:c|a[cf]|bb[cf])'
	*/
	public function test_buildRegexpFromList_1cc75402()
	{
		$this->assertSame(
			'(?:c|a[cf]|bb[cf])',
			RegexpHelper::buildRegexpFromList(array('ac', 'af', 'bbc', 'bbf', 'c'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['^example.org$', '.example.org$', '^localhost$', '.localhost$'], ["specialChars" => ["^" => "^", "$" => "$"]]) returns '(?:\\.|^)(?:example\\.org|localhost)$'
	*/
	public function test_buildRegexpFromList_d463a304()
	{
		$this->assertSame(
			'(?:\\.|^)(?:example\\.org|localhost)$',
			RegexpHelper::buildRegexpFromList(
				array('^example.org$', '.example.org$', '^localhost$', '.localhost$'),
				array('specialChars' => array('^' => '^', '$' => '$'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['xixix', 'xoxox']) returns 'x(?:ixi|oxo)x'
	*/
	public function test_buildRegexpFromList_b33646c2()
	{
		$this->assertSame(
			'x(?:ixi|oxo)x',
			RegexpHelper::buildRegexpFromList(array('xixix', 'xoxox'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['xixix', 'xixox', 'xoxox', 'xoxix']) returns 'x[io]x[io]x'
	*/
	public function test_buildRegexpFromList_c7d616c2()
	{
		$this->assertSame(
			'x[io]x[io]x',
			RegexpHelper::buildRegexpFromList(array('xixix', 'xixox', 'xoxox', 'xoxix'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['afoo', 'abar', 'bbfoo', 'bbbar', 'a', 'bb']) returns '(?:a|bb)(?:bar|foo)?'
	*/
	public function test_buildRegexpFromList_b02e083b()
	{
		$this->assertSame(
			'(?:a|bb)(?:bar|foo)?',
			RegexpHelper::buildRegexpFromList(array('afoo', 'abar', 'bbfoo', 'bbbar', 'a', 'bb'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'ay', 'bx', 'by']) returns '[ab][xy]'
	*/
	public function test_buildRegexpFromList_4619fd0f()
	{
		$this->assertSame(
			'[ab][xy]',
			RegexpHelper::buildRegexpFromList(array('ax', 'ay', 'bx', 'by'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'ay', 'bx', 'by', 'c']) returns '(?:c|[ab][xy])'
	*/
	public function test_buildRegexpFromList_f7523978()
	{
		$this->assertSame(
			'(?:c|[ab][xy])',
			RegexpHelper::buildRegexpFromList(array('ax', 'ay', 'bx', 'by', 'c'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'ay', 'bx', 'by', 'x', 'y']) returns '[ab]?[xy]'
	*/
	public function test_buildRegexpFromList_660fc1a9()
	{
		$this->assertSame(
			'[ab]?[xy]',
			RegexpHelper::buildRegexpFromList(array('ax', 'ay', 'bx', 'by', 'x', 'y'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'ay', 'bbx', 'bby', 'c']) returns '(?:c|a[xy]|bb[xy])'
	*/
	public function test_buildRegexpFromList_58a1b850()
	{
		$this->assertSame(
			'(?:c|a[xy]|bb[xy])',
			RegexpHelper::buildRegexpFromList(array('ax', 'ay', 'bbx', 'bby', 'c'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ax', 'ay', 'bx', 'by', 'c', 'ddx', 'ddy']) returns '(?:c|dd[xy]|[ab][xy])'
	*/
	public function test_buildRegexpFromList_23c1bd26()
	{
		$this->assertSame(
			'(?:c|dd[xy]|[ab][xy])',
			RegexpHelper::buildRegexpFromList(array('ax', 'ay', 'bx', 'by', 'c', 'ddx', 'ddy'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['']) returns ''
	*/
	public function test_buildRegexpFromList_5cbf14d3()
	{
		$this->assertSame(
			'',
			RegexpHelper::buildRegexpFromList(array(''))
		);
	}

	/**
	* @testdox buildRegexpFromList(['', '']) returns ''
	*/
	public function test_buildRegexpFromList_418d8f44()
	{
		$this->assertSame(
			'',
			RegexpHelper::buildRegexpFromList(array('', ''))
		);
	}

	/**
	* @testdox buildRegexpFromList(['ad', 'bd'], ["specialChars" => ["d" => "\\d"]]) returns '[ab]\\d'
	*/
	public function test_buildRegexpFromList_5b18c2d1()
	{
		$this->assertSame(
			'[ab]\\d',
			RegexpHelper::buildRegexpFromList(
				array('ad', 'bd'),
				array('specialChars' => array('d' => '\\d'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['a', 'ax', 'ad', 'd', 'dx', 'dd'], ["specialChars" => ["d" => "\\d"]]) returns '[\\da][\\dx]?'
	*/
	public function test_buildRegexpFromList_4032006c()
	{
		$this->assertSame(
			'[\\da][\\dx]?',
			RegexpHelper::buildRegexpFromList(
				array('a', 'ax', 'ad', 'd', 'dx', 'dd'),
				array('specialChars' => array('d' => '\\d'))
			)
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'bar', 'y', 'z']) returns '(?:[yz]|bar|foo)'
	*/
	public function test_buildRegexpFromList_561fe181()
	{
		$this->assertSame(
			'(?:[yz]|bar|foo)',
			RegexpHelper::buildRegexpFromList(array('foo', 'bar', 'y', 'z'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['foo', 'bar', 'baz', 'y', 'z']) returns '(?:[yz]|ba[rz]|foo)'
	*/
	public function test_buildRegexpFromList_c80c5a7f()
	{
		$this->assertSame(
			'(?:[yz]|ba[rz]|foo)',
			RegexpHelper::buildRegexpFromList(array('foo', 'bar', 'baz', 'y', 'z'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['a', 'aacc', 'aadd', 'bbcc', 'bbdd']) returns '(?:a(?:a(?:cc|dd))?|bb(?:cc|dd))'
	*/
	public function test_buildRegexpFromList_140f192a()
	{
		$this->assertSame(
			'(?:a(?:a(?:cc|dd))?|bb(?:cc|dd))',
			RegexpHelper::buildRegexpFromList(array('a', 'aacc', 'aadd', 'bbcc', 'bbdd'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aa', 'bb', 'aacc', 'aadd', 'bbcc', 'bbdd']) returns '(?:aa|bb)(?:cc|dd)?'
	*/
	public function test_buildRegexpFromList_fa3816e9()
	{
		$this->assertSame(
			'(?:aa|bb)(?:cc|dd)?',
			RegexpHelper::buildRegexpFromList(array('aa', 'bb', 'aacc', 'aadd', 'bbcc', 'bbdd'))
		);
	}

	/**
	* @testdox buildRegexpFromList(['aa', 'bb', 'aaccxx', 'aaddxx', 'bbccxx', 'bbddxx', 'aaccyy', 'aaddyy', 'bbccyy', 'bbddyy']) returns '(?:aa|bb)(?:(?:cc|dd)(?:xx|yy))?'
	*/
	public function test_buildRegexpFromList_4eeb6994()
	{
		$this->assertSame(
			'(?:aa|bb)(?:(?:cc|dd)(?:xx|yy))?',
			RegexpHelper::buildRegexpFromList(array('aa', 'bb', 'aaccxx', 'aaddxx', 'bbccxx', 'bbddxx', 'aaccyy', 'aaddyy', 'bbccyy', 'bbddyy'))
		);
	}
	// End of content generated by ../../../scripts/patchRegexpHelperTest.php

	/**
	* @expectedException RuntimeException
	* @expectedExceptionMessage Invalid UTF-8 string
	* @testdox buildRegexpFromList() throws a RuntimeException if any word is not legal UTF-8
	*/
	public function testUTF8Exception()
	{
		RegexpHelper::buildRegexpFromList(array("\xff\xff"));
	}

	/**
	* @testdox parse() can parse plain regexps
	*/
	public function testCanParseRegexps1()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => 'foo',
				'tokens'    => array()
			),
			RegexpHelper::parse(
				'#foo#'
			)
		);
	}

	/**
	* @testdox parse() throws a RuntimeException if delimiters can't be parsed
	* @expectedException RuntimeException
	* @expectedExceptionMessage Could not parse regexp delimiters
	*/
	public function testInvalidRegexpsException1()
	{
		RegexpHelper::parse('#foo/iD');
	}

	/**
	* @testdox parse() parses pattern modifiers
	*/
	public function testCanParseRegexps2()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => 'iD',
				'regexp'    => 'foo',
				'tokens'    => array()
			),
			RegexpHelper::parse(
				'#foo#iD'
			)
		);
	}

	/**
	* @testdox parse() parses character classes
	*/
	public function testCanParseRegexps3()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '[a-z]',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 5,
						'type' => 'characterClass',
						'content' => 'a-z',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#[a-z]#'
			)
		);
	}

	/**
	* @testdox parse() parses character classes with quantifiers
	*/
	public function testCanParseRegexps4()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '[a-z]+',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 6,
						'type' => 'characterClass',
						'content' => 'a-z',
						'quantifiers' => '+'
					)
				)
			),
			RegexpHelper::parse(
				'#[a-z]+#'
			)
		);
	}

	/**
	* @testdox parse() parses character classes that end with an escaped ]
	*/
	public function testCanParseRegexps5()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '[a-z\\]]',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 7,
						'type' => 'characterClass',
						'content' => 'a-z\\]',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#[a-z\\]]#'
			)
		);
	}

	/**
	* @testdox parse() throws a RuntimeException if a character class is not properly closed
	* @expectedException RuntimeException
	* @expectedExceptionMessage Could not find matching bracket from pos 0
	*/
	public function testInvalidRegexpsException2()
	{
		RegexpHelper::parse('#[a-z)#');
	}

	/**
	* @testdox parse() correctly parses escaped brackets
	*/
	public function testCanParseRegexps6()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '\\[x\\]',
				'tokens'    => array()
			),
			RegexpHelper::parse(
				'#\\[x\\]#'
			)
		);
	}

	/**
	* @testdox parse() correctly parses escaped parentheses
	*/
	public function testCanParseRegexps7()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '\\(x\\)',
				'tokens'    => array()
			),
			RegexpHelper::parse(
				'#\\(x\\)#'
			)
		);
	}

	/**
	* @testdox parse() parses non-capturing subpatterns
	*/
	public function testCanParseRegexps8()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?:x+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 3,
						'type' => 'nonCapturingSubpatternStart',
						'options' => '',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 5,
						'len' => 1,
						'type' => 'nonCapturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?:x+)#'
			)
		);
	}

	/**
	* @testdox parse() parses non-capturing subpatterns with atomic grouping
	*/
	public function testCanParseRegexps8b()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?>x+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 3,
						'type' => 'nonCapturingSubpatternStart',
						'subtype' => 'atomic',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 5,
						'len' => 1,
						'type' => 'nonCapturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?>x+)#'
			)
		);
	}

	/**
	* @testdox parse() parses non-capturing subpatterns with quantifiers
	*/
	public function testCanParseRegexps9()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?:x+)++',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 3,
						'type' => 'nonCapturingSubpatternStart',
						'options' => '',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 5,
						'len' => 3,
						'type' => 'nonCapturingSubpatternEnd',
						'quantifiers' => '++'
					)
				)
			),
			RegexpHelper::parse(
				'#(?:x+)++#'
			)
		);
	}

	/**
	* @testdox parse() parses non-capturing subpatterns with options
	*/
	public function testCanParseRegexps10()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?i:x+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 4,
						'type' => 'nonCapturingSubpatternStart',
						'options' => 'i',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 6,
						'len' => 1,
						'type' => 'nonCapturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?i:x+)#'
			)
		);
	}

	/**
	* @testdox parse() parses option settings
	*/
	public function testCanParseRegexps11()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?i)abc',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 4,
						'type' => 'option',
						'options' => 'i'
					)
				)
			),
			RegexpHelper::parse(
				'#(?i)abc#'
			)
		);
	}

	/**
	* @testdox parse() parses named subpatterns using the (?<name>) syntax
	*/
	public function testCanParseRegexps12()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?<foo>x+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 7,
						'type' => 'capturingSubpatternStart',
						'name' => 'foo',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 9,
						'len' => 1,
						'type' => 'capturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?<foo>x+)#'
			)
		);
	}

	/**
	* @testdox parse() parses named subpatterns using the (?P<name>) syntax
	*/
	public function testCanParseRegexps13()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?P<foo>x+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 8,
						'type' => 'capturingSubpatternStart',
						'name' => 'foo',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 10,
						'len' => 1,
						'type' => 'capturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?P<foo>x+)#'
			)
		);
	}

	/**
	* @testdox parse() parses named subpatterns using the (?'name') syntax
	*/
	public function testCanParseRegexps14()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => "(?'foo'x+)",
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 7,
						'type' => 'capturingSubpatternStart',
						'name' => 'foo',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 9,
						'len' => 1,
						'type' => 'capturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				"#(?'foo'x+)#"
			)
		);
	}

	/**
	* @testdox parse() parses capturing subpatterns
	*/
	public function testCanParseRegexps15()
	{
		$this->assertEquals(
			array(
				'delimiter' => '/',
				'modifiers' => '',
				'regexp'    => '(x+)(abc\\d+)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 1,
						'type' => 'capturingSubpatternStart',
						'content' => 'x+',
						'endToken' => 1
					),
					array(
						'pos' => 3,
						'len' => 1,
						'type' => 'capturingSubpatternEnd',
						'quantifiers' => ''
					),
					array(
						'pos' => 4,
						'len' => 1,
						'type' => 'capturingSubpatternStart',
						'content' => 'abc\\d+',
						'endToken' => 3
					),
					array(
						'pos' => 11,
						'len' => 1,
						'type' => 'capturingSubpatternEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'/(x+)(abc\\d+)/'
			)
		);
	}

	/**
	* @testdox parse() throws a RuntimeException if an unmatched right parenthesis is found
	* @expectedException RuntimeException
	* @expectedExceptionMessage Could not find matching pattern start for right parenthesis at pos 3
	*/
	public function testInvalidRegexpsException4()
	{
		RegexpHelper::parse('#a-z)#');
	}

	/**
	* @testdox parse() throws a RuntimeException if an unmatched left parenthesis is found
	* @expectedException RuntimeException
	* @expectedExceptionMessage Could not find matching pattern end for left parenthesis at pos 0
	*/
	public function testInvalidRegexpsException5()
	{
		RegexpHelper::parse('#(a-z#');
	}

	/**
	* @testdox parse() throws a RuntimeException on unsupported subpatterns
	* @expectedException RuntimeException
	* @expectedExceptionMessage Unsupported subpattern type at pos 0
	*/
	public function testInvalidRegexpsUnsupportedSubpatternException()
	{
		RegexpHelper::parse('#(?(condition)yes-pattern|no-pattern)#');
	}

	/**
	* @testdox parse() parses lookahead assertions
	*/
	public function testCanParseRegexps16()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?=foo)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 3,
						'type' => 'lookaheadAssertionStart',
						'content' => 'foo',
						'endToken' => 1
					),
					array(
						'pos' => 6,
						'len' => 1,
						'type' => 'lookaheadAssertionEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?=foo)#'
			)
		);
	}

	/**
	* @testdox parse() parses negative lookahead assertions
	*/
	public function testCanParseRegexps17()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?!foo)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 3,
						'type' => 'negativeLookaheadAssertionStart',
						'content' => 'foo',
						'endToken' => 1
					),
					array(
						'pos' => 6,
						'len' => 1,
						'type' => 'negativeLookaheadAssertionEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?!foo)#'
			)
		);
	}

	/**
	* @testdox parse() parses lookbehind assertions
	*/
	public function testCanParseRegexps18()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?<=foo)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 4,
						'type' => 'lookbehindAssertionStart',
						'content' => 'foo',
						'endToken' => 1
					),
					array(
						'pos' => 7,
						'len' => 1,
						'type' => 'lookbehindAssertionEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?<=foo)#'
			)
		);
	}

	/**
	* @testdox parse() parses negative lookbehind assertions
	*/
	public function testCanParseRegexps19()
	{
		$this->assertEquals(
			array(
				'delimiter' => '#',
				'modifiers' => '',
				'regexp'    => '(?<!foo)',
				'tokens'    => array(
					array(
						'pos' => 0,
						'len' => 4,
						'type' => 'negativeLookbehindAssertionStart',
						'content' => 'foo',
						'endToken' => 1
					),
					array(
						'pos' => 7,
						'len' => 1,
						'type' => 'negativeLookbehindAssertionEnd',
						'quantifiers' => ''
					)
				)
			),
			RegexpHelper::parse(
				'#(?<!foo)#'
			)
		);
	}


	/**
	* @testdox pcreToJs() can convert plain regexps
	*/
	public function testConvertRegexp1()
	{
		$this->assertEquals(
			'/foo/',
			RegexpHelper::pcreToJs('#foo#')
		);
	}

	/**
	* @testdox pcreToJs() escapes forward slashes
	*/
	public function testConvertRegexpEscape()
	{
		$this->assertEquals(
			'/fo\\/o/',
			RegexpHelper::pcreToJs('#fo/o#')
		);
	}

	/**
	* @testdox pcreToJs() does not double-escape forward slashes that are already escaped
	*/
	public function testConvertRegexpNoDoubleEscape()
	{
		$this->assertEquals(
			'/fo\\/o/',
			RegexpHelper::pcreToJs('#fo\\/o#')
		);
	}

	/**
	* @testdox pcreToJs() does not "eat" backslashes while escaping forward slashes
	*/
	public function testConvertRegexpDoesNotEatEscapedBackslashes()
	{
		$this->assertEquals(
			'/fo\\\\\\/o/',
			RegexpHelper::pcreToJs('#fo\\\\/o#')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with the "i" modifier
	*/
	public function testConvertRegexp2()
	{
		$this->assertEquals(
			'/foo/i',
			RegexpHelper::pcreToJs('#foo#i')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with capturing subpatterns
	*/
	public function testConvertRegexp3()
	{
		$this->assertEquals(
			'/f(o)o/',
			RegexpHelper::pcreToJs('#f(o)o#')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with non-capturing subpatterns
	*/
	public function testConvertRegexp4()
	{
		$this->assertEquals(
			'/f(?:o)o/',
			RegexpHelper::pcreToJs('#f(?:o)o#')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with non-capturing subpatterns with a quantifier
	*/
	public function testConvertRegexp5()
	{
		$this->assertEquals(
			'/f(?:oo)+/',
			RegexpHelper::pcreToJs('#f(?:oo)+#')
		);
	}

	/**
	* @testdox pcreToJs() converts greedy quantifiers to normal quantifiers in non-capturing subpatterns
	*/
	public function testConvertRegexp5b()
	{
		$this->assertEquals(
			'/f(?:o)+(?:o)*/',
			RegexpHelper::pcreToJs('#f(?:o)++(?:o)*+#')
		);
	}

	/**
	* @testdox pcreToJs() throws a RuntimeException on options (?i)
	* @expectedException RuntimeException
	* @expectedExceptionMessage Regexp options are not supported
	*/
	public function testConvertRegexpException1()
	{
		RegexpHelper::pcreToJs('#(?i)x#');
	}

	/**
	* @testdox pcreToJs() throws a RuntimeException on subpattern options (?i:)
	* @expectedException RuntimeException
	* @expectedExceptionMessage Subpattern options are not supported
	*/
	public function testConvertRegexpException2()
	{
		RegexpHelper::pcreToJs('#(?i:x)#');
	}

	/**
	* @testdox pcreToJs() can convert regexps with character classes with a quantifier
	*/
	public function testConvertRegexp6()
	{
		$this->assertEquals(
			'/[a-z]+/',
			RegexpHelper::pcreToJs('#[a-z]+#')
		);
	}

	/**
	* @testdox pcreToJs() converts greedy quantifiers to normal quantifiers in character classes
	*/
	public function testConvertRegexp6b()
	{
		$this->assertEquals(
			'/[a-z]+[a-z]*/',
			RegexpHelper::pcreToJs('/[a-z]++[a-z]*+/')
		);
	}

	/**
	* @testdox pcreToJs() replaces \pL with the full character range in character classes
	*/
	public function testConvertRegexp7()
	{
		$unicodeRange = '(?:[a-zA-Z]-?)*(?:\\\\u[0-9A-F]{4}-?)*';
		$this->assertRegexp(
			'#^/\\[0-9' . $unicodeRange . '\\]/$#D',
			RegexpHelper::pcreToJs('#[0-9\\pL]#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \p{L} with the full character range in character classes
	*/
	public function testConvertRegexp7b()
	{
		$unicodeRange = '(?:[a-zA-Z]-?)*(?:\\\\u[0-9A-F]{4}-?)*';
		$this->assertRegexp(
			'#^/\\[0-9' . $unicodeRange . '\\]/$#D',
			RegexpHelper::pcreToJs('#[0-9\\p{L}]#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \pL outside of character classes with a character class containing the full character range
	*/
	public function testConvertRegexp8()
	{
		$unicodeRange = '(?:[a-zA-Z]-?)*(?:\\\\u[0-9A-F]{4}-?)*';
		$this->assertRegexp(
			'#^/\\[' . $unicodeRange . '\\]00\\[' . $unicodeRange . '\\]/$#D',
			RegexpHelper::pcreToJs('#\\pL00\\pL#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \p{L} outside of character classes with a character class containing the full character range
	*/
	public function testConvertRegexp8b()
	{
		$unicodeRange = '(?:[a-zA-Z]-?)*(?:\\\\u[0-9A-F]{4}-?)*';
		$this->assertRegexp(
			'#^/\\[' . $unicodeRange . '\\]00\\[' . $unicodeRange . '\\]/$#D',
			RegexpHelper::pcreToJs('#\\p{L}00\\p{L}#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \p{^L} with a character class containing the full character range
	*/
	public function testConvertRegexp8c()
	{
		$unicodeRange = '(?:[a-zA-Z]-?)*(?:\\\\u[0-9A-F]{4}-?)*';

		$this->assertRegexp(
			'#^/\\[' . $unicodeRange . '\\]/$#D',
			RegexpHelper::pcreToJs('#\\p{^L}#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \p{^L} with a character class equivalent to \PL
	*/
	public function testConvertRegexp8d()
	{
		$this->assertSame(
			RegexpHelper::pcreToJs('#\\PL#'),
			RegexpHelper::pcreToJs('#\\p{^L}#')
		);
	}

	/**
	* @testdox pcreToJs() replaces \P{^L} with a character class equivalent to \pL
	*/
	public function testConvertRegexp8e()
	{
		$this->assertSame(
			RegexpHelper::pcreToJs('#\\pL#'),
			RegexpHelper::pcreToJs('#\\P{^L}#')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with lookahead assertions
	*/
	public function testConvertRegexpLookahead()
	{
		$this->assertEquals(
			'/(?=foo)|(?=bar)/',
			RegexpHelper::pcreToJs('#(?=foo)|(?=bar)#')
		);
	}

	/**
	* @testdox pcreToJs() can convert regexps with negative lookahead assertions
	*/
	public function testConvertRegexpNegativeLookahead()
	{
		$this->assertEquals(
			'/(?!foo)|(?!bar)/',
			RegexpHelper::pcreToJs('#(?!foo)|(?!bar)#')
		);
	}

	/**
	* @testdox pcreToJs() throws a RuntimeException on lookbehind assertions
	* @expectedException RuntimeException
	* @expectedExceptionMessage Lookbehind assertions are not supported
	*/
	public function testConvertRegexpExceptionOnLookbehind()
	{
		RegexpHelper::pcreToJs('#(?<=foo)x#');
	}

	/**
	* @testdox pcreToJs() throws a RuntimeException on negative lookbehind assertions
	* @expectedException RuntimeException
	* @expectedExceptionMessage Negative lookbehind assertions are not supported
	*/
	public function testConvertRegexpExceptionOnNegativeLookbehind()
	{
		RegexpHelper::pcreToJs('#(?<!foo)x#');
	}

	/**
	* @testdox pcreToJs() converts . to [\s\S] outside of character classes if the "s" modifier is set
	*/
	public function testConvertRegexpDotAll()
	{
		$this->assertEquals(
			'/foo([\\s\\S]*)bar/',
			RegexpHelper::pcreToJs('#foo(.*)bar#s')
		);
	}

	/**
	* @testdox pcreToJs() does not convert . to [\s\S] if the "s" modifier is not set
	*/
	public function testConvertRegexpDotWithoutDotAll()
	{
		$this->assertEquals(
			'/foo(.*)bar/',
			RegexpHelper::pcreToJs('#foo(.*)bar#')
		);
	}

	/**
	* @testdox pcreToJs() does not convert . inside of character classes
	*/
	public function testConvertRegexpDotInCharacterClasses()
	{
		$this->assertEquals(
			'/foo[.]+bar/',
			RegexpHelper::pcreToJs('#foo[.]+bar#s')
		);
	}

	/**
	* @testdox pcreToJs() converts named captures into normal captures
	*/
	public function testConvertRegexpNamedCaptures()
	{
		$this->assertEquals(
			'/x([0-9]+)([a-z]+)x/',
			RegexpHelper::pcreToJs('#x(?<foo>[0-9]+)(?<bar>[a-z]+)x#', $map)
		);
	}

	/**
	* @testdox pcreToJs() replaces its second parameter with an array that maps named captures to their index
	*/
	public function testConvertRegexpNamedCapturesMap()
	{
		$map = null;

		$this->assertEquals(
			'/x([0-9]+)([a-z]+)x/',
			RegexpHelper::pcreToJs('#x(?<foo>[0-9]+)(?<bar>[a-z]+)x#', $map)
		);

		$this->assertEquals(
			array('foo' => 1, 'bar' => 2),
			$map
		);
	}

	/**
	* NOTE: this is a regression test
	* @testdox pcreToJs() correctly converts /(?:foo)(?<z>bar)/ to /(?:foo)(bar)/
	*/
	public function testConvertNamedSubatternAfterNormalSubpattern()
	{
		$map = null;

		$this->assertSame(
			'/(?:foo)(bar)/',
			RegexpHelper::pcreToJs('/(?:foo)(?<z>bar)/', $map)
		);
	}

	public function getWordsLists()
	{
		return array(
			array(
				'foo',
				array('foo')
			),
			array(
				'foo',
				array('foo', 'foo')
			),
			array(
				'a',
				array('a')
			),
			array(
				'a',
				array('a', 'a')
			),
			array(
				'ap(?:ple|ril)',
				array('apple', 'april')
			),
			array(
				'ba[rz]',
				array('bar', 'baz')
			),
			array(
				'fool?',
				array('foo', 'fool')
			),
			array(
				'ax(?:ed)?',
				array('ax', 'axed')
			),
/*
			array(
				'apple.*?',
				array('apple', 'apple*'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.*?',
				array('apple*', 'applepie'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.+?',
				array('apple*', 'applepie'),
				array('specialChars' => array('*' => '.+?'))
			),
			array(
				'apple.*?',
				array('apple*', 'apple'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.*',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.*?', '+' => '.*'))
			),
			array(
				'apple.+',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.+?', '+' => '.+'))
			),
			array(
				'apple.*',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.*', '+' => '.+'))
			),
*/
			array(
				'.',
				array('a', '.'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h.p',
				array('hip', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h(?:i|.p)',
				array('hi', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h.?',
				array('h', 'h.'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h(?:.|\\d\\d)',
				array('h.', 'hd'),
				array('specialChars' => array('.' => '.', 'd' => '\\d\\d'))
			),
			array(
				'h(?:...........|otel)',
				array('hXXXXXXXXXXX', 'h\\^$.[]()+*?', 'hotel'),
				array('specialChars' => array('X' => '.'))
			),
			array(
				'z(?:..........|ebra)',
				array('zdDhHsSvVwW', 'z..........', 'zebra'),
				array('specialChars' => array(
					'\\d'=> '\\d', '\\D'=> '\\D', '\\h'=> '\\h', '\\H'=> '\\H',
					'\\s'=> '\\s', '\\S'=> '\\S', '\\v'=> '\\v', '\\V'=> '\\V',
					'\\w'=> '\\w', '\\W'=> '\\W', '.' => '.'
				))
			),
			array(
				'h(?:$|.)',
				array('h$', 'h.'),
				array('specialChars' => array('.' => '.', '$' => '$'))
			),
			array(
				'[-!:<=>\\#\\\\\\]}$()*+.?[{|^]',
				str_split('!#$()*+-.:<=>?[\\]^{|}', 1)
			),
			array(
				'(?:x|^)y',
				array('xy', '^y'),
				array('specialChars' => array('^' => '^'))
			),
			array(
				'x(?:y|$)',
				array('xy', 'x$'),
				array('specialChars' => array('$' => '$'))
			),
			array(
				'(?:bar|foo)',
				array('foo', 'bar')
			),
			array(
				'(?=[\\\\*])(?:\\*foo|\\\\bar)',
				array('*foo', '\\bar'),
				array('useLookahead' => true)
			),
			array(
				'(?:.|bar)',
				// Here, we build a regexp that matches one single character or the word "bar"
				// The joker ? is replaced by the special character .
				array('?', 'bar'),
				array('specialChars' => array('?' => '.'), 'useLookahead' => true)
			),
			array(
				'[ab]',
				array('a', 'b')
			),
			array(
				'[♠♣♥♦]',
				array('♠', '♣', '♥', '♦')
			),
			array(
				'[ls]ock',
				array('lock', 'sock')
			),
			array(
				'(?=[af])a?foo',
				array('foo', 'afoo'),
				array('useLookahead' => true)
			),
			array(
				'bo[ao]st',
				array('boast', 'boost')
			),
			array(
				'pe?st',
				array('pest', 'pst')
			),
			array(
				'bo[ao]?st',
				array('boast', 'boost', 'bost')
			),
			array(
				'b(?:e|oo)st',
				array('boost', 'best')
			),
			array(
				'b(?:oo)?st',
				array('boost', 'bst')
			),
			array(
				'b(?:[eu]|oo)st',
				array('best', 'boost', 'bust')
			),
			array(
				'(?:b(?:oo)?st|cool)',
				array('boost', 'bst', 'cool')
			),
			array(
				'(?:b(?:oo)?|co)st',
				array('boost', 'bst', 'cost')
			),
			array(
				'aa[xy]',
				array('aax', 'aay', 'aax', 'aay')
			),
			array(
				'[ab]aa[xy]',
				array('aaax', 'aaay', 'baax', 'baay')
			),
			array(
				'(?:a|bb)aa[xy]',
				array('aaax', 'aaay', 'bbaax', 'bbaay')
			),
			array(
				'aaa?[xy]',
				array('aaax', 'aaay', 'aax', 'aay')
			),
			array(
				'(?:ab|cd)[xy]',
				array('abx', 'aby', 'cdx', 'cdy')
			),
			array(
				'(?:a|bb)(?:xx|yy)',
				array('axx', 'ayy', 'bbxx', 'bbyy')
			),
			array(
				'(?:c|(?:a|bb)(?:xx|yy))',
				array('axx', 'ayy', 'bbxx', 'bbyy', 'c')
			),
			array(
				// Ensure it doesn't become (?:c|(?:a|bb)(?:xx|yy)|azz) even though it would be
				// shorter, because having fewer alternations at the top level is more important
				'(?:c|a(?:xx|yy|zz)|bb(?:xx|yy))',
				array('axx', 'ayy', 'azz', 'bbxx', 'bbyy', 'c')
			),
			array(
				// We don't merge "ac", "af", "bbc" and "bbf" tails because the result
				// (?:c|(?:a|bb)[cf]) is neither more performant nor shorter
				'(?:c|a[cf]|bb[cf])',
				array('ac', 'af', 'bbc', 'bbf', 'c')
			),
			array(
				// Typical regexp used in UrlConfig for matching hostnames and subdomains
				'(?:\.|^)(?:example\\.org|localhost)$',
				array('^example.org$', '.example.org$', '^localhost$', '.localhost$'),
				array('specialChars' => array('^' => '^', '$' => '$'))
			),
			array(
				'x(?:ixi|oxo)x',
				array('xixix', 'xoxox')
			),
			array(
				'x[io]x[io]x',
				array('xixix', 'xixox', 'xoxox', 'xoxix')
			),
			array(
				'(?:a|bb)(?:bar|foo)?',
				array('afoo', 'abar', 'bbfoo', 'bbbar', 'a', 'bb')
			),
			array(
				'[ab][xy]',
				array('ax', 'ay', 'bx', 'by')
			),
			array(
				'(?:c|[ab][xy])',
				array('ax', 'ay', 'bx', 'by', 'c')
			),
			array(
				'[ab]?[xy]',
				array('ax', 'ay', 'bx', 'by', 'x', 'y')
			),
			// Ensure that merging tails does not create subpatterns
			array(
				'(?:c|a[xy]|bb[xy])',
				array('ax', 'ay', 'bbx', 'bby', 'c')
			),
			array(
				'(?:c|dd[xy]|[ab][xy])',
				array('ax', 'ay', 'bx', 'by', 'c', 'ddx', 'ddy')
			),
			// Those two only exist to make sure nothing bad happens (e.g. no infinite loop)
			array(
				'',
				array('')
			),
			array(
				'',
				array('', '')
			),
			array(
				'[ab]\\d',
				array('ad', 'bd'),
				array('specialChars' => array('d' => '\\d'))
			),
			array(
				'[\\da][\\dx]?',
				array('a', 'ax', 'ad', 'd', 'dx', 'dd'),
				array('specialChars' => array('d' => '\\d'))
			),
			// Ensure that character classes made from single characters appear first in alternation
			array(
				'(?:[yz]|bar|foo)',
				array('foo', 'bar', 'y', 'z')
			),
			array(
				'(?:[yz]|ba[rz]|foo)',
				array('foo', 'bar', 'baz', 'y', 'z')
			),
			array(
				'(?:a(?:a(?:cc|dd))?|bb(?:cc|dd))',
				array('a', 'aacc', 'aadd', 'bbcc', 'bbdd')
			),
			array(
				'(?:aa|bb)(?:cc|dd)?',
				array('aa', 'bb', 'aacc', 'aadd', 'bbcc', 'bbdd')
			),
			array(
				'(?:aa|bb)(?:(?:cc|dd)(?:xx|yy))?',
				array(
					'aa', 'bb',
					'aaccxx', 'aaddxx', 'bbccxx', 'bbddxx',
					'aaccyy', 'aaddyy', 'bbccyy', 'bbddyy'
				)
			)
		);
	}
}