<?php

namespace s9e\TextFormatter\Tests\Configurator\Helpers;

use s9e\TextFormatter\Tests\Test;
use s9e\TextFormatter\Configurator\Helpers\RegexpBuilder;

/**
* @covers s9e\TextFormatter\Configurator\Helpers\RegexpBuilder
*/
class RegexpBuilderTest extends Test
{
	// Start of content generated by ../../../scripts/patchRegexpBuilderTest.php
	/**
	* @testdox fromList(['foo']) returns 'foo'
	*/
	public function test_2E6B327F()
	{
		$this->fromListTestCase(0);
	}

	/**
	* @testdox fromList(['foo', 'foo']) returns 'foo'
	*/
	public function test_EFC21F10()
	{
		$this->fromListTestCase(1);
	}

	/**
	* @testdox fromList(['FOO', 'foo']) returns '(?:FOO|foo)'
	*/
	public function test_D43386C()
	{
		$this->fromListTestCase(2);
	}

	/**
	* @testdox fromList(['FOO', 'foo'], ["caseInsensitive" => true]) returns 'foo'
	*/
	public function test_D2493E8A()
	{
		$this->fromListTestCase(3);
	}

	/**
	* @testdox fromList(['a']) returns 'a'
	*/
	public function test_37E7519F()
	{
		$this->fromListTestCase(4);
	}

	/**
	* @testdox fromList(['a', 'a']) returns 'a'
	*/
	public function test_46ECDB38()
	{
		$this->fromListTestCase(5);
	}

	/**
	* @testdox fromList(['/']) returns '\\/'
	*/
	public function test_E2479414()
	{
		$this->fromListTestCase(6);
	}

	/**
	* @testdox fromList(['/'], ["delimiter" => "#"]) returns '/'
	*/
	public function test_B3EEE700()
	{
		$this->fromListTestCase(7);
	}

	/**
	* @testdox fromList(['#'], ["delimiter" => "#"]) returns '\\#'
	*/
	public function test_A1D05928()
	{
		$this->fromListTestCase(8);
	}

	/**
	* @testdox fromList(['apple', 'april']) returns 'ap(?:ple|ril)'
	*/
	public function test_8B59A499()
	{
		$this->fromListTestCase(9);
	}

	/**
	* @testdox fromList(['bar', 'baz']) returns 'ba[rz]'
	*/
	public function test_E7FFB86F()
	{
		$this->fromListTestCase(10);
	}

	/**
	* @testdox fromList(['foo', 'fool']) returns 'fool?'
	*/
	public function test_1DFF1AB5()
	{
		$this->fromListTestCase(11);
	}

	/**
	* @testdox fromList(['ax', 'axed']) returns 'ax(?:ed)?'
	*/
	public function test_B4F156BE()
	{
		$this->fromListTestCase(12);
	}

	/**
	* @testdox fromList(['!', '#', '$', '(', ')', '*', '+', '-', '.', ':', '<', '=', '>', '?', '[', '\\', ']', '^', '{', '|', '}']) returns '[-!#$()*+.:<=>?[\\\\\\]{|}^]'
	*/
	public function test_C7373394()
	{
		$this->fromListTestCase(13);
	}

	/**
	* @testdox fromList(['xy', '^y'], ["specialChars" => ["^" => "^"]]) returns '(?:x|^)y'
	*/
	public function test_8A71E271()
	{
		$this->fromListTestCase(14);
	}

	/**
	* @testdox fromList(['xy', 'x$'], ["specialChars" => ["$" => "$"]]) returns 'x(?:y|$)'
	*/
	public function test_13BA1BFA()
	{
		$this->fromListTestCase(15);
	}

	/**
	* @testdox fromList(['foo', 'bar']) returns '(?:bar|foo)'
	*/
	public function test_A3302107()
	{
		$this->fromListTestCase(16);
	}

	/**
	* @testdox fromList(['*foo', '\\bar'], ["useLookahead" => true]) returns '(?=[*\\\\])(?:\\*foo|\\\\bar)'
	*/
	public function test_3CCC7313()
	{
		$this->fromListTestCase(17);
	}

	/**
	* @testdox fromList(['?', 'bar'], ["specialChars" => ["?" => "."], "useLookahead" => true]) returns '(?:.|bar)'
	*/
	public function test_7FFB138D()
	{
		$this->fromListTestCase(18);
	}

	/**
	* @testdox fromList(['a', 'b']) returns '[ab]'
	*/
	public function test_C90B2457()
	{
		$this->fromListTestCase(19);
	}

	/**
	* @testdox fromList(['♠', '♣', '♥', '♦']) returns '[♠♣♥♦]'
	*/
	public function test_6335367B()
	{
		$this->fromListTestCase(20);
	}

	/**
	* @testdox fromList(['♠', '♣', '♥', '♦', '.'], ["specialChars" => ["." => "."]]) returns '.'
	*/
	public function test_D9B63085()
	{
		$this->fromListTestCase(21);
	}

	/**
	* @testdox fromList(['lock', 'sock']) returns '[ls]ock'
	*/
	public function test_A3CF0B4D()
	{
		$this->fromListTestCase(22);
	}

	/**
	* @testdox fromList(['foo', 'afoo'], ["useLookahead" => true]) returns '(?=[af])a?foo'
	*/
	public function test_8613531B()
	{
		$this->fromListTestCase(23);
	}

	/**
	* @testdox fromList(['boast', 'boost']) returns 'bo[ao]st'
	*/
	public function test_4BBAD47D()
	{
		$this->fromListTestCase(24);
	}

	/**
	* @testdox fromList(['pest', 'pst']) returns 'pe?st'
	*/
	public function test_596D7420()
	{
		$this->fromListTestCase(25);
	}

	/**
	* @testdox fromList(['boast', 'boost', 'bost']) returns 'bo[ao]?st'
	*/
	public function test_E644DCEB()
	{
		$this->fromListTestCase(26);
	}

	/**
	* @testdox fromList(['boost', 'best']) returns 'b(?:e|oo)st'
	*/
	public function test_AEB9F217()
	{
		$this->fromListTestCase(27);
	}

	/**
	* @testdox fromList(['boost', 'bst']) returns 'b(?:oo)?st'
	*/
	public function test_BE3CCBA2()
	{
		$this->fromListTestCase(28);
	}

	/**
	* @testdox fromList(['best', 'boost', 'bust']) returns 'b(?:[eu]|oo)st'
	*/
	public function test_9753E32D()
	{
		$this->fromListTestCase(29);
	}

	/**
	* @testdox fromList(['boost', 'bst', 'cool']) returns '(?:b(?:oo)?st|cool)'
	*/
	public function test_9A764069()
	{
		$this->fromListTestCase(30);
	}

	/**
	* @testdox fromList(['boost', 'bst', 'cost']) returns '(?:b(?:oo)?|co)st'
	*/
	public function test_53994AB6()
	{
		$this->fromListTestCase(31);
	}

	/**
	* @testdox fromList(['aax', 'aay', 'aax', 'aay']) returns 'aa[xy]'
	*/
	public function test_560C8444()
	{
		$this->fromListTestCase(32);
	}

	/**
	* @testdox fromList(['aaax', 'aaay', 'baax', 'baay']) returns '[ab]aa[xy]'
	*/
	public function test_F3709BEF()
	{
		$this->fromListTestCase(33);
	}

	/**
	* @testdox fromList(['aaax', 'aaay', 'bbaax', 'bbaay']) returns '(?:a|bb)aa[xy]'
	*/
	public function test_7C889532()
	{
		$this->fromListTestCase(34);
	}

	/**
	* @testdox fromList(['aaax', 'aaay', 'aax', 'aay']) returns 'aaa?[xy]'
	*/
	public function test_77F7FECB()
	{
		$this->fromListTestCase(35);
	}

	/**
	* @testdox fromList(['abx', 'aby', 'cdx', 'cdy']) returns '(?:ab|cd)[xy]'
	*/
	public function test_62E02B3A()
	{
		$this->fromListTestCase(36);
	}

	/**
	* @testdox fromList(['axx', 'ayy', 'bbxx', 'bbyy']) returns '(?:a|bb)(?:xx|yy)'
	*/
	public function test_8A86C707()
	{
		$this->fromListTestCase(37);
	}

	/**
	* @testdox fromList(['axx', 'ayy', 'bbxx', 'bbyy', 'c']) returns '(?:c|(?:a|bb)(?:xx|yy))'
	*/
	public function test_59FB8E0()
	{
		$this->fromListTestCase(38);
	}

	/**
	* @testdox fromList(['axx', 'ayy', 'azz', 'bbxx', 'bbyy', 'c']) returns '(?:c|a(?:xx|yy|zz)|bb(?:xx|yy))'
	*/
	public function test_EA302659()
	{
		$this->fromListTestCase(39);
	}

	/**
	* @testdox fromList(['ac', 'af', 'bbc', 'bbf', 'c']) returns '(?:c|a[cf]|bb[cf])'
	*/
	public function test_1CC75402()
	{
		$this->fromListTestCase(40);
	}

	/**
	* @testdox fromList(['^example.org$', '.example.org$', '^localhost$', '.localhost$'], ["specialChars" => ["^" => "^", "$" => "$"]]) returns '(?:\\.|^)(?:example\\.org|localhost)$'
	*/
	public function test_D463A304()
	{
		$this->fromListTestCase(41);
	}

	/**
	* @testdox fromList(['xixix', 'xoxox']) returns 'x(?:ixi|oxo)x'
	*/
	public function test_B33646C2()
	{
		$this->fromListTestCase(42);
	}

	/**
	* @testdox fromList(['xixix', 'xixox', 'xoxox', 'xoxix']) returns 'x[io]x[io]x'
	*/
	public function test_C7D616C2()
	{
		$this->fromListTestCase(43);
	}

	/**
	* @testdox fromList(['afoo', 'abar', 'bbfoo', 'bbbar', 'a', 'bb']) returns '(?:a|bb)(?:bar|foo)?'
	*/
	public function test_B02E083B()
	{
		$this->fromListTestCase(44);
	}

	/**
	* @testdox fromList(['ax', 'ay', 'bx', 'by']) returns '[ab][xy]'
	*/
	public function test_4619FD0F()
	{
		$this->fromListTestCase(45);
	}

	/**
	* @testdox fromList(['ax', 'ay', 'bx', 'by', 'c']) returns '(?:c|[ab][xy])'
	*/
	public function test_F7523978()
	{
		$this->fromListTestCase(46);
	}

	/**
	* @testdox fromList(['ax', 'ay', 'bx', 'by', 'x', 'y']) returns '[ab]?[xy]'
	*/
	public function test_660FC1A9()
	{
		$this->fromListTestCase(47);
	}

	/**
	* @testdox fromList(['ax', 'ay', 'bbx', 'bby', 'c']) returns '(?:c|a[xy]|bb[xy])'
	*/
	public function test_58A1B850()
	{
		$this->fromListTestCase(48);
	}

	/**
	* @testdox fromList(['ax', 'ay', 'bx', 'by', 'c', 'ddx', 'ddy']) returns '(?:c|dd[xy]|[ab][xy])'
	*/
	public function test_23C1BD26()
	{
		$this->fromListTestCase(49);
	}

	/**
	* @testdox fromList(['']) returns ''
	*/
	public function test_5CBF14D3()
	{
		$this->fromListTestCase(50);
	}

	/**
	* @testdox fromList(['', '']) returns ''
	*/
	public function test_418D8F44()
	{
		$this->fromListTestCase(51);
	}

	/**
	* @testdox fromList(['ad', 'bd'], ["specialChars" => ["d" => "\\d"]]) returns '[ab]\\d'
	*/
	public function test_5B18C2D1()
	{
		$this->fromListTestCase(52);
	}

	/**
	* @testdox fromList(['a', 'ax', 'ad', 'd', 'dx', 'dd'], ["specialChars" => ["d" => "\\d"]]) returns '[\\da][\\dx]?'
	*/
	public function test_4032006C()
	{
		$this->fromListTestCase(53);
	}

	/**
	* @testdox fromList(['foo', 'bar', 'y', 'z']) returns '(?:[yz]|bar|foo)'
	*/
	public function test_561FE181()
	{
		$this->fromListTestCase(54);
	}

	/**
	* @testdox fromList(['foo', 'bar', 'baz', 'y', 'z']) returns '(?:[yz]|ba[rz]|foo)'
	*/
	public function test_C80C5A7F()
	{
		$this->fromListTestCase(55);
	}

	/**
	* @testdox fromList(['a', 'aacc', 'aadd', 'bbcc', 'bbdd']) returns '(?:a(?:a(?:cc|dd))?|bb(?:cc|dd))'
	*/
	public function test_140F192A()
	{
		$this->fromListTestCase(56);
	}

	/**
	* @testdox fromList(['aa', 'bb', 'aacc', 'aadd', 'bbcc', 'bbdd']) returns '(?:aa|bb)(?:cc|dd)?'
	*/
	public function test_FA3816E9()
	{
		$this->fromListTestCase(57);
	}

	/**
	* @testdox fromList(['aa', 'bb', 'aaccxx', 'aaddxx', 'bbccxx', 'bbddxx', 'aaccyy', 'aaddyy', 'bbccyy', 'bbddyy']) returns '(?:aa|bb)(?:(?:cc|dd)(?:xx|yy))?'
	*/
	public function test_4EEB6994()
	{
		$this->fromListTestCase(58);
	}

	/**
	* @testdox fromList(['^foo$', '^foo'], ["specialChars" => ["^" => "^", "$" => "$"]]) returns '^foo'
	*/
	public function test_CDAEB9BF()
	{
		$this->fromListTestCase(59);
	}

	/**
	* @testdox fromList(['^foo$', 'foo$'], ["specialChars" => ["^" => "^", "$" => "$"]]) returns 'foo$'
	*/
	public function test_58B353C0()
	{
		$this->fromListTestCase(60);
	}

	/**
	* @testdox fromList(['bfoo', 'bfoob'], ["specialChars" => ["b" => "\\b"]]) returns '\\bfoo'
	*/
	public function test_6985D5F9()
	{
		$this->fromListTestCase(61);
	}

	/**
	* @testdox fromList(['apple', 'apple*'], ["specialChars" => ["*" => ".*?"]]) returns 'apple.*?'
	*/
	public function test_C73BB118()
	{
		$this->fromListTestCase(62);
	}

	/**
	* @testdox fromList(['apple*', 'applepie'], ["specialChars" => ["*" => ".*?"]]) returns 'apple.*?'
	*/
	public function test_BC8587F9()
	{
		$this->fromListTestCase(63);
	}

	/**
	* @testdox fromList(['apple*', 'applepie'], ["specialChars" => ["*" => ".+?"]]) returns 'apple.+?'
	*/
	public function test_C445AC48()
	{
		$this->fromListTestCase(64);
	}

	/**
	* @testdox fromList(['apple*', 'apple'], ["specialChars" => ["*" => ".*?"]]) returns 'apple.*?'
	*/
	public function test_3CD709C9()
	{
		$this->fromListTestCase(65);
	}

	/**
	* @testdox fromList(['apple*', 'apple+'], ["specialChars" => ["*" => ".*?", "+" => ".*"]]) returns 'apple.*'
	*/
	public function test_E13691C4()
	{
		$this->fromListTestCase(66);
	}

	/**
	* @testdox fromList(['apple*', 'apple+'], ["specialChars" => ["*" => ".+?", "+" => ".+"]]) returns 'apple.+'
	*/
	public function test_C1CD7108()
	{
		$this->fromListTestCase(67);
	}

	/**
	* @testdox fromList(['apple*', 'apple+'], ["specialChars" => ["*" => ".*", "+" => ".+"]]) returns 'apple.*'
	*/
	public function test_9C89464A()
	{
		$this->fromListTestCase(68);
	}

	/**
	* @testdox fromList(['applepie', 'lemonpie', 'pie', '*pie'], ["specialChars" => ["*" => ".*"]]) returns '.*pie'
	*/
	public function test_C7A9B0A5()
	{
		$this->fromListTestCase(69);
	}

	/**
	* @testdox fromList(['*pie*', 'lemonpie'], ["specialChars" => ["*" => ".*"]]) returns '.*pie.*'
	*/
	public function test_C54CFAF6()
	{
		$this->fromListTestCase(70);
	}

	/**
	* @testdox fromList(['*pie*', 'lemonpie', 'banana'], ["specialChars" => ["*" => ".*"]]) returns '(?:.*pie.*|banana)'
	*/
	public function test_34EFDA6F()
	{
		$this->fromListTestCase(71);
	}

	/**
	* @testdox fromList(['^foo$', '^foo+'], ["specialChars" => ["^" => "^", "$" => "$", "+" => ".+"]]) returns '^foo(?:$|.+)'
	*/
	public function test_F3C52183()
	{
		$this->fromListTestCase(72);
	}

	/**
	* @testdox fromList(['^foo$', '^foo*'], ["specialChars" => ["^" => "^", "$" => "$", "*" => ".*"]]) returns '^foo.*'
	*/
	public function test_57BBBDB4()
	{
		$this->fromListTestCase(73);
	}

	/**
	* @testdox fromList(['food', 'foo+'], ["specialChars" => ["d" => "\\d", "+" => ".+"]]) returns 'foo.+'
	*/
	public function test_3C407EB8()
	{
		$this->fromListTestCase(74);
	}

	/**
	* @testdox fromList(['foo*', 'foo+'], ["specialChars" => ["*" => "\\w*", "+" => ".+"]]) returns 'foo(?:\\w*|.+)'
	*/
	public function test_7A1B32CC()
	{
		$this->fromListTestCase(75);
	}

	/**
	* @testdox fromList(['foo?', 'foo+'], ["specialChars" => ["?" => "\\w?", "+" => ".+"]]) returns 'foo(?:.+|\\w?)'
	*/
	public function test_44A90030()
	{
		$this->fromListTestCase(76);
	}

	/**
	* @testdox fromList(['fooB', 'foo+'], ["specialChars" => ["B" => "\\B", "+" => ".+"]]) returns 'foo(?:.+|\\B)'
	*/
	public function test_16E28B20()
	{
		$this->fromListTestCase(77);
	}

	/**
	* @testdox fromList(['+foo+', 'fooB'], ["specialChars" => ["B" => "\\B", "+" => ".+"]]) returns '(?:.+foo.+|foo\\B)'
	*/
	public function test_94F12345()
	{
		$this->fromListTestCase(78);
	}

	/**
	* @testdox fromList(['+foo+', 'foo', 'bar'], ["specialChars" => ["+" => ".+"]]) returns '(?:.+foo.+|bar|foo)'
	*/
	public function test_C55ADFEF()
	{
		$this->fromListTestCase(79);
	}

	/**
	* @testdox fromList(['+foo+', '+foo', 'bar'], ["specialChars" => ["+" => ".+"]]) returns '(?:.+foo.*|bar)'
	*/
	public function test_69C9F3E0()
	{
		$this->fromListTestCase(80);
	}

	/**
	* @testdox fromList(['+foo+', '+foo'], ["specialChars" => ["+" => ".+"]]) returns '.+foo.*'
	*/
	public function test_6AA5ABFC()
	{
		$this->fromListTestCase(81);
	}

	/**
	* @testdox fromList(['++', 'a'], ["specialChars" => ["+" => ".+"]]) returns '(?:a|.+.+)'
	*/
	public function test_51B52D9E()
	{
		$this->fromListTestCase(82);
	}

	/**
	* @testdox fromList(['a', '.'], ["specialChars" => ["." => "."]]) returns '.'
	*/
	public function test_C29CED5()
	{
		$this->fromListTestCase(83);
	}

	/**
	* @testdox fromList(['hip', 'hop', 'h.p'], ["specialChars" => ["." => "."]]) returns 'h.p'
	*/
	public function test_6AB3A485()
	{
		$this->fromListTestCase(84);
	}

	/**
	* @testdox fromList(['hi', 'hop', 'h.p'], ["specialChars" => ["." => "."]]) returns 'h(?:i|.p)'
	*/
	public function test_8FC43CB0()
	{
		$this->fromListTestCase(85);
	}

	/**
	* @testdox fromList(['h', 'h.'], ["specialChars" => ["." => "."]]) returns 'h.?'
	*/
	public function test_9BA9174B()
	{
		$this->fromListTestCase(86);
	}

	/**
	* @testdox fromList(['h.', 'hd'], ["specialChars" => ["." => ".", "d" => "\\d\\d"]]) returns 'h(?:.|\\d\\d)'
	*/
	public function test_A1628B44()
	{
		$this->fromListTestCase(87);
	}

	/**
	* @testdox fromList(['hXXXXXXXXXXX', 'h\\^$.[]()+*?', 'hotel'], ["specialChars" => ["X" => "."]]) returns 'h(?:...........|otel)'
	*/
	public function test_71D6E963()
	{
		$this->fromListTestCase(88);
	}

	/**
	* @testdox fromList(['zdDhHsSvVwW', 'z..........', 'zebra'], ["specialChars" => ["d" => "\\d", "D" => "D", "h" => "\\h", "H" => "\\H", "s" => "\\s", "S" => "S", "v" => "\\v", "V" => "\\V", "w" => "\\w", "W" => "W", "." => "."]]) returns 'z(?:..........|ebra)'
	*/
	public function test_4C2C4778()
	{
		$this->fromListTestCase(89);
	}

	/**
	* @testdox fromList(['m.', 'mb'], ["specialChars" => ["." => ".", "b" => "\\b"]]) returns 'm(?:.|\\b)'
	*/
	public function test_B05A865()
	{
		$this->fromListTestCase(90);
	}

	/**
	* @testdox fromList(['m.', 'mB'], ["specialChars" => ["." => ".", "B" => "\\B"]]) returns 'm(?:.|\\B)'
	*/
	public function test_823A9663()
	{
		$this->fromListTestCase(91);
	}

	/**
	* @testdox fromList(['m.', 'mA'], ["specialChars" => ["." => ".", "A" => "\\A"]]) returns 'm(?:.|\\A)'
	*/
	public function test_E58BCD87()
	{
		$this->fromListTestCase(92);
	}

	/**
	* @testdox fromList(['m.', 'mZ'], ["specialChars" => ["." => ".", "Z" => "\\Z"]]) returns 'm(?:.|\\Z)'
	*/
	public function test_95245C1()
	{
		$this->fromListTestCase(93);
	}

	/**
	* @testdox fromList(['m.', 'mz'], ["specialChars" => ["." => ".", "z" => "\\z"]]) returns 'm(?:.|\\z)'
	*/
	public function test_806D7BC7()
	{
		$this->fromListTestCase(94);
	}

	/**
	* @testdox fromList(['m.', 'mG'], ["specialChars" => ["." => ".", "G" => "\\G"]]) returns 'm(?:.|\\G)'
	*/
	public function test_2AE97A4F()
	{
		$this->fromListTestCase(95);
	}

	/**
	* @testdox fromList(['m.', 'mQ'], ["specialChars" => ["." => ".", "Q" => "\\Q"]]) returns 'm(?:.|\\Q)'
	*/
	public function test_A1145284()
	{
		$this->fromListTestCase(96);
	}

	/**
	* @testdox fromList(['m.', 'mE'], ["specialChars" => ["." => ".", "E" => "\\E"]]) returns 'm(?:.|\\E)'
	*/
	public function test_6FC8E8F7()
	{
		$this->fromListTestCase(97);
	}

	/**
	* @testdox fromList(['m.', 'mK'], ["specialChars" => ["." => ".", "K" => "\\K"]]) returns 'm(?:.|\\K)'
	*/
	public function test_6F5D139E()
	{
		$this->fromListTestCase(98);
	}

	/**
	* @testdox fromList(['h$', 'h.'], ["specialChars" => ["." => ".", "$" => "$"]]) returns 'h(?:$|.)'
	*/
	public function test_34005F32()
	{
		$this->fromListTestCase(99);
	}

	/**
	* @testdox fromList(['h?', 'ha'], ["specialChars" => ["?" => ".?"]]) returns 'h.?'
	*/
	public function test_8DB4D1E0()
	{
		$this->fromListTestCase(100);
	}

	/**
	* @testdox fromList(['h.', 'hi', 'hit'], ["specialChars" => ["." => ".?"]]) returns 'h(?:.|it)?'
	*/
	public function test_2ABBC9E3()
	{
		$this->fromListTestCase(101);
	}

	/**
	* @testdox fromList(['a.c.e', 'a.ce', 'ac.e', 'ace', 'acde', 'abce', 'abcde'], ["specialChars" => ["." => ".?"]]) returns 'a.?c.?e'
	*/
	public function test_8E336686()
	{
		$this->fromListTestCase(102);
	}

	/**
	* @testdox fromList(['h????', 'hello', 'heart'], ["specialChars" => ["?" => ".?"]]) returns 'h.?.?.?.?'
	*/
	public function test_8E765F3B()
	{
		$this->fromListTestCase(103);
	}

	/**
	* @testdox fromList(['x', 'xx', 'xxx']) returns 'xx?x?'
	*/
	public function test_A55EF35C()
	{
		$this->fromListTestCase(104);
	}

	/**
	* @testdox fromList(['d', 'dd', 'ddd'], ["specialChars" => ["d" => "\\d"]]) returns '\\d\\d?\\d?'
	*/
	public function test_69AB5342()
	{
		$this->fromListTestCase(105);
	}
	// End of content generated by ../../../scripts/patchRegexpBuilderTest.php

	protected function fromListTestCase($k)
	{
		$data = $this->getWordsLists();

		$expected = $data[$k][0];
		$words    = $data[$k][1];
		$options  = (isset($data[$k][2])) ? $data[$k][2] : array();

		$this->assertSame($expected, RegexpBuilder::fromList($words, $options));
	}

	/**
	* @expectedException RuntimeException
	* @expectedExceptionMessage Invalid UTF-8 string
	* @testdox fromList() throws a RuntimeException if any word is not legal UTF-8
	*/
	public function testUTF8Exception()
	{
		RegexpBuilder::fromList(array("\xff\xff"));
	}

	public function getWordsLists()
	{
		return array(
			array(
				'foo',
				array('foo')
			),
			array(
				'foo',
				array('foo', 'foo')
			),
			array(
				'(?:FOO|foo)',
				array('FOO', 'foo')
			),
			array(
				'foo',
				array('FOO', 'foo'),
				array('caseInsensitive' => true)
			),
			array(
				'a',
				array('a')
			),
			array(
				'a',
				array('a', 'a')
			),
			array(
				'\\/',
				array('/'),
			),
			array(
				'/',
				array('/'),
				array('delimiter' => '#')
			),
			array(
				'\\#',
				array('#'),
				array('delimiter' => '#')
			),
			array(
				'ap(?:ple|ril)',
				array('apple', 'april')
			),
			array(
				'ba[rz]',
				array('bar', 'baz')
			),
			array(
				'fool?',
				array('foo', 'fool')
			),
			array(
				'ax(?:ed)?',
				array('ax', 'axed')
			),
			array(
				'[-!#$()*+.:<=>?[\\\\\\]{|}^]',
				str_split('!#$()*+-.:<=>?[\\]^{|}', 1)
			),
			array(
				'(?:x|^)y',
				array('xy', '^y'),
				array('specialChars' => array('^' => '^'))
			),
			array(
				'x(?:y|$)',
				array('xy', 'x$'),
				array('specialChars' => array('$' => '$'))
			),
			array(
				'(?:bar|foo)',
				array('foo', 'bar')
			),
			array(
				'(?=[*\\\\])(?:\\*foo|\\\\bar)',
				array('*foo', '\\bar'),
				array('useLookahead' => true)
			),
			array(
				'(?:.|bar)',
				// Here, we build a regexp that matches one single character or the word "bar"
				// The joker ? is replaced by the special character .
				array('?', 'bar'),
				array('specialChars' => array('?' => '.'), 'useLookahead' => true)
			),
			array(
				'[ab]',
				array('a', 'b')
			),
			array(
				'[♠♣♥♦]',
				array('♠', '♣', '♥', '♦')
			),
			array(
				'.',
				array('♠', '♣', '♥', '♦', '.'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'[ls]ock',
				array('lock', 'sock')
			),
			array(
				'(?=[af])a?foo',
				array('foo', 'afoo'),
				array('useLookahead' => true)
			),
			array(
				'bo[ao]st',
				array('boast', 'boost')
			),
			array(
				'pe?st',
				array('pest', 'pst')
			),
			array(
				'bo[ao]?st',
				array('boast', 'boost', 'bost')
			),
			array(
				'b(?:e|oo)st',
				array('boost', 'best')
			),
			array(
				'b(?:oo)?st',
				array('boost', 'bst')
			),
			array(
				'b(?:[eu]|oo)st',
				array('best', 'boost', 'bust')
			),
			array(
				'(?:b(?:oo)?st|cool)',
				array('boost', 'bst', 'cool')
			),
			array(
				'(?:b(?:oo)?|co)st',
				array('boost', 'bst', 'cost')
			),
			array(
				'aa[xy]',
				array('aax', 'aay', 'aax', 'aay')
			),
			array(
				'[ab]aa[xy]',
				array('aaax', 'aaay', 'baax', 'baay')
			),
			array(
				'(?:a|bb)aa[xy]',
				array('aaax', 'aaay', 'bbaax', 'bbaay')
			),
			array(
				'aaa?[xy]',
				array('aaax', 'aaay', 'aax', 'aay')
			),
			array(
				'(?:ab|cd)[xy]',
				array('abx', 'aby', 'cdx', 'cdy')
			),
			array(
				'(?:a|bb)(?:xx|yy)',
				array('axx', 'ayy', 'bbxx', 'bbyy')
			),
			array(
				'(?:c|(?:a|bb)(?:xx|yy))',
				array('axx', 'ayy', 'bbxx', 'bbyy', 'c')
			),
			array(
				// Ensure it doesn't become (?:c|(?:a|bb)(?:xx|yy)|azz) even though it would be
				// shorter, because having fewer alternations at the top level is more important
				'(?:c|a(?:xx|yy|zz)|bb(?:xx|yy))',
				array('axx', 'ayy', 'azz', 'bbxx', 'bbyy', 'c')
			),
			array(
				// We don't merge "ac", "af", "bbc" and "bbf" tails because the result
				// (?:c|(?:a|bb)[cf]) is neither more performant nor shorter
				'(?:c|a[cf]|bb[cf])',
				array('ac', 'af', 'bbc', 'bbf', 'c')
			),
			array(
				// Typical regexp used in UrlConfig for matching hostnames and subdomains
				'(?:\.|^)(?:example\\.org|localhost)$',
				array('^example.org$', '.example.org$', '^localhost$', '.localhost$'),
				array('specialChars' => array('^' => '^', '$' => '$'))
			),
			array(
				'x(?:ixi|oxo)x',
				array('xixix', 'xoxox')
			),
			array(
				'x[io]x[io]x',
				array('xixix', 'xixox', 'xoxox', 'xoxix')
			),
			array(
				'(?:a|bb)(?:bar|foo)?',
				array('afoo', 'abar', 'bbfoo', 'bbbar', 'a', 'bb')
			),
			array(
				'[ab][xy]',
				array('ax', 'ay', 'bx', 'by')
			),
			array(
				'(?:c|[ab][xy])',
				array('ax', 'ay', 'bx', 'by', 'c')
			),
			array(
				'[ab]?[xy]',
				array('ax', 'ay', 'bx', 'by', 'x', 'y')
			),
			// Ensure that merging tails does not create subpatterns
			array(
				'(?:c|a[xy]|bb[xy])',
				array('ax', 'ay', 'bbx', 'bby', 'c')
			),
			array(
				'(?:c|dd[xy]|[ab][xy])',
				array('ax', 'ay', 'bx', 'by', 'c', 'ddx', 'ddy')
			),
			// Those two only exist to make sure nothing bad happens (e.g. no infinite loop)
			array(
				'',
				array('')
			),
			array(
				'',
				array('', '')
			),
			array(
				'[ab]\\d',
				array('ad', 'bd'),
				array('specialChars' => array('d' => '\\d'))
			),
			array(
				'[\\da][\\dx]?',
				array('a', 'ax', 'ad', 'd', 'dx', 'dd'),
				array('specialChars' => array('d' => '\\d'))
			),
			// Ensure that character classes made from single characters appear first in alternation
			array(
				'(?:[yz]|bar|foo)',
				array('foo', 'bar', 'y', 'z')
			),
			array(
				'(?:[yz]|ba[rz]|foo)',
				array('foo', 'bar', 'baz', 'y', 'z')
			),
			array(
				'(?:a(?:a(?:cc|dd))?|bb(?:cc|dd))',
				array('a', 'aacc', 'aadd', 'bbcc', 'bbdd')
			),
			array(
				'(?:aa|bb)(?:cc|dd)?',
				array('aa', 'bb', 'aacc', 'aadd', 'bbcc', 'bbdd')
			),
			array(
				'(?:aa|bb)(?:(?:cc|dd)(?:xx|yy))?',
				array(
					'aa', 'bb',
					'aaccxx', 'aaddxx', 'bbccxx', 'bbddxx',
					'aaccyy', 'aaddyy', 'bbccyy', 'bbddyy'
				)
			),
			array(
				'^foo',
				array('^foo$', '^foo'),
				array('specialChars' => array('^' => '^', '$' => '$'))
			),
			array(
				'foo$',
				array('^foo$', 'foo$'),
				array('specialChars' => array('^' => '^', '$' => '$'))
			),
			array(
				'\\bfoo',
				array('bfoo', 'bfoob'),
				array('specialChars' => array('b' => '\\b'))
			),
			array(
				'apple.*?',
				array('apple', 'apple*'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.*?',
				array('apple*', 'applepie'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.+?',
				array('apple*', 'applepie'),
				array('specialChars' => array('*' => '.+?'))
			),
			array(
				'apple.*?',
				array('apple*', 'apple'),
				array('specialChars' => array('*' => '.*?'))
			),
			array(
				'apple.*',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.*?', '+' => '.*'))
			),
			array(
				'apple.+',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.+?', '+' => '.+'))
			),
			array(
				'apple.*',
				array('apple*', 'apple+'),
				array('specialChars' => array('*' => '.*', '+' => '.+'))
			),
			array(
				'.*pie',
				array('applepie', 'lemonpie', 'pie', '*pie'),
				array('specialChars' => array('*' => '.*'))
			),
			array(
				'.*pie.*',
				array('*pie*', 'lemonpie'),
				array('specialChars' => array('*' => '.*'))
			),
			array(
				'(?:.*pie.*|banana)',
				array('*pie*', 'lemonpie', 'banana'),
				array('specialChars' => array('*' => '.*'))
			),
			array(
				'^foo(?:$|.+)',
				array('^foo$', '^foo+'),
				array('specialChars' => array('^' => '^', '$' => '$', '+' => '.+'))
			),
			array(
				'^foo.*',
				array('^foo$', '^foo*'),
				array('specialChars' => array('^' => '^', '$' => '$', '*' => '.*'))
			),
			array(
				'foo.+',
				array('food', 'foo+'),
				array('specialChars' => array('d' => '\\d', '+' => '.+'))
			),
			array(
				'foo(?:\\w*|.+)',
				array('foo*', 'foo+'),
				array('specialChars' => array('*' => '\\w*', '+' => '.+'))
			),
			array(
				'foo(?:.+|\\w?)',
				array('foo?', 'foo+'),
				array('specialChars' => array('?' => '\\w?', '+' => '.+'))
			),
			array(
				'foo(?:.+|\\B)',
				array('fooB', 'foo+'),
				array('specialChars' => array('B' => '\\B', '+' => '.+'))
			),
			array(
				'(?:.+foo.+|foo\\B)',
				array('+foo+', 'fooB'),
				array('specialChars' => array('B' => '\\B', '+' => '.+'))
			),
			array(
				'(?:.+foo.+|bar|foo)',
				array('+foo+', 'foo', 'bar'),
				array('specialChars' => array('+' => '.+'))
			),
			array(
				'(?:.+foo.*|bar)',
				array('+foo+', '+foo', 'bar'),
				array('specialChars' => array('+' => '.+'))
			),
			array(
				'.+foo.*',
				array('+foo+', '+foo'),
				array('specialChars' => array('+' => '.+'))
			),
			array(
				'(?:a|.+.+)',
				array('++', 'a'),
				array('specialChars' => array('+' => '.+'))
			),
			array(
				'.',
				array('a', '.'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h.p',
				array('hip', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h(?:i|.p)',
				array('hi', 'hop', 'h.p'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h.?',
				array('h', 'h.'),
				array('specialChars' => array('.' => '.'))
			),
			array(
				'h(?:.|\\d\\d)',
				array('h.', 'hd'),
				array('specialChars' => array('.' => '.', 'd' => '\\d\\d'))
			),
			array(
				'h(?:...........|otel)',
				array('hXXXXXXXXXXX', 'h\\^$.[]()+*?', 'hotel'),
				array('specialChars' => array('X' => '.'))
			),
			/**
			* @link http://docs.php.net/manual/en/regexp.reference.escape.php
			*/
			array(
				'z(?:..........|ebra)',
				array('zdDhHsSvVwW', 'z..........', 'zebra'),
				array('specialChars' => array(
					'd' => '\\d', 'D' => 'D', 'h' => '\\h', 'H' => '\\H',
					's' => '\\s', 'S' => 'S', 'v' => '\\v', 'V' => '\\V',
					'w' => '\\w', 'W' => 'W', '.' => '.'
				))
			),
			array(
				'm(?:.|\\b)',
				array('m.', 'mb'),
				array('specialChars' => array('.' => '.', 'b' => '\\b'))
			),
			array(
				'm(?:.|\\B)',
				array('m.', 'mB'),
				array('specialChars' => array('.' => '.', 'B' => '\\B'))
			),
			array(
				'm(?:.|\\A)',
				array('m.', 'mA'),
				array('specialChars' => array('.' => '.', 'A' => '\\A'))
			),
			array(
				'm(?:.|\\Z)',
				array('m.', 'mZ'),
				array('specialChars' => array('.' => '.', 'Z' => '\\Z'))
			),
			array(
				'm(?:.|\\z)',
				array('m.', 'mz'),
				array('specialChars' => array('.' => '.', 'z' => '\\z'))
			),
			array(
				'm(?:.|\\G)',
				array('m.', 'mG'),
				array('specialChars' => array('.' => '.', 'G' => '\\G'))
			),
			array(
				'm(?:.|\\Q)',
				array('m.', 'mQ'),
				array('specialChars' => array('.' => '.', 'Q' => '\\Q'))
			),
			array(
				'm(?:.|\\E)',
				array('m.', 'mE'),
				array('specialChars' => array('.' => '.', 'E' => '\\E'))
			),
			array(
				'm(?:.|\\K)',
				array('m.', 'mK'),
				array('specialChars' => array('.' => '.', 'K' => '\\K'))
			),
			array(
				'h(?:$|.)',
				array('h$', 'h.'),
				array('specialChars' => array('.' => '.', '$' => '$'))
			),
			array(
				'h.?',
				array('h?', 'ha'),
				array('specialChars' => array('?' => '.?'))
			),
			array(
				'h(?:.|it)?',
				array('h.', 'hi', 'hit'),
				array('specialChars' => array('.' => '.?'))
			),
			array(
				'a.?c.?e',
				array('a.c.e', 'a.ce', 'ac.e', 'ace', 'acde', 'abce', 'abcde'),
				array('specialChars' => array('.' => '.?'))
			),
			array(
				'h.?.?.?.?',
				array('h????', 'hello', 'heart'),
				array('specialChars' => array('?' => '.?'))
			),
			array(
				'xx?x?',
				array('x', 'xx', 'xxx')
			),
			array(
				'\\d\\d?\\d?',
				array('d', 'dd', 'ddd'),
				array('specialChars' => array('d' => '\\d'))
			),
		);
	}
}