<?php

/**
* @package   s9e\TextFormatter
* @copyright Copyright (c) 2010-2013 The s9e Authors
* @license   http://www.opensource.org/licenses/mit-license.php The MIT License
*/
namespace s9e\TextFormatter\Configurator\Helpers;

use DOMDocument;
use DOMNode;
use RuntimeException;

class XPathParser
{
	/**
	* Parse an XPath expression
	*
	* @link http://www.w3.org/TR/xpath/
	*
	* @param  string      $expr      XPath expression
	* @param  string      $tokenName Start token, e.g. "Expr" or "LocationPath"
	* @return DOMDocument
	*/
	public static function parse($expr, $tokenName = 'Expr')
	{
		$dom = new DOMDocument;

		self::appendExpr($dom, $expr, $tokenName);

		return $dom;
	}

	/**
	* Append the representation of given expression
	*
	* @param  DOMNode $node      Host node
	* @param  string  $expr      XPath expression
	* @param  string  $tokenName Start token
	* @return void
	*/
	protected static function appendExpr(DOMNode $node, $expr, $tokenName)
	{
		$regexp = self::$regexps[$tokenName];

		if (!preg_match($regexp, $expr, $matches, PREG_OFFSET_CAPTURE))
		{
			throw new RuntimeException("Cannot parse '" . $expr . "' as " . $tokenName);
		}

		$doc  = ($node instanceof DOMDocument) ? $node : $node->ownerDocument;
		$node = $node->appendChild($doc->createElement($tokenName));

		$pos = 0;
		foreach ($matches as $k => list($matchText, $matchPos))
		{
			if ($matchPos  === -1
			 || $matchText === ''
			 || !preg_match('/^[A-Z]\\w*\\d$/', $k))
			{
				continue;
			}

			if ($matchPos !== $pos)
			{
				$node->appendChild(
					$node->ownerDocument->createTextNode(substr($expr, $pos, $matchPos - $pos))
				);
			}

			$tokenName = rtrim($k, '0123456789');
			self::appendExpr($node, $matchText, $tokenName);
			$pos = $matchPos + strlen($matchText);
		}

		if ($pos < strlen($expr))
		{
			$node->appendChild($node->ownerDocument->createTextNode(substr($expr, $pos)));
		}
	}

	/**
	* @var array Regexps used for matching tokens
	*
	* @see scripts/patchXPathParser.php
	*/
	protected static $regexps = [
		'AbbreviatedAbsoluteLocationPath' => '(^\\s*(?://\\s*(?<RelativeLocationPath1>(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?&RelativeLocationPath))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\])*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*)))\\s*$)',
		'AbbreviatedAxisSpecifier' => '(^\\s*(?:@?)\\s*$)',
		'AbbreviatedRelativeLocationPath' => '(^\\s*(?:(?<Step1>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?&RelativeLocationPath))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\])*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?)))\\s*//\\s*(?<RelativeLocationPath2>(?<RelativeLocationPath>(?&Step)\\s*(?://?\\s*(?&Step)\\s*)*)))\\s*$)',
		'AbbreviatedStep' => '(^\\s*(?:\\.\\.?)\\s*$)',
		'AbsoluteLocationPath' => '(^\\s*(?://?\\s*(?<RelativeLocationPath1>(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?&RelativeLocationPath))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?&AbbreviatedAbsoluteLocationPath))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\])*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath2>(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath))))\\s*$)',
		'AdditiveExpr' => '(^\\s*(?:(?<MultiplicativeExpr1>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?&MultiplicativeExpr)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?))\\s*(?:[-+]\\s*(?<MultiplicativeExpr2>(?&MultiplicativeExpr)))?)\\s*$)',
		'AndExpr' => '(^\\s*(?:(?<EqualityExpr1>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?&AndExpr)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?))\\s*(?:and\\s*(?<AndExpr2>(?<AndExpr>(?&EqualityExpr)\\s*(?:and\\s*(?&AndExpr))?)))?)\\s*$)',
		'Argument' => '(^\\s*(?:(?<Expr1>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))))\\s*$)',
		'AxisName' => '(^\\s*(?:ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*$)',
		'AxisSpecifier' => '(^\\s*(?:(?<AxisName1>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self))\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier2>(?<AbbreviatedAxisSpecifier>@?)))\\s*$)',
		'Digits' => '(^\\s*(?:[0-9]+)\\s*$)',
		'EqualityExpr' => '(^\\s*(?:(?<RelationalExpr1>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?&RelationalExpr)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?))\\s*(?:!?=\\s*(?<RelationalExpr2>(?&RelationalExpr)))?)\\s*$)',
		'Expr' => '(^\\s*(?:(?<OrExpr1>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?&OrExpr))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*$)',
		'FilterExpr' => '(^\\s*(?:(?<PrimaryExpr1>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?&PrimaryExpr)\\s*(?&Predicate)*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?&NCName)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?&NodeType)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\))))\\s*(?<Predicate2>(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\]))*)\\s*$)',
		'FunctionCall' => '(^\\s*(?:(?<FunctionName1>(?<FunctionName>(?!(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node))(?<QName>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*\\(\\s*(?:(?<Argument2>(?<Argument>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?&FunctionName)\\s*\\(\\s*(?:(?&Argument)\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?&NCName)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?&NodeType)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))))\\s*(?:,\\s*(?<Argument3>(?&Argument))\\s*)*\\s*)?\\s*\\))\\s*$)',
		'FunctionName' => '(^\\s*(?:(?!(?<NodeType1>(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)))(?<QName2>(?<QName>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*$)',
		'Literal' => '(^\\s*(?:"[^"]*"\\s*|\\s*\'[^\']*\')\\s*$)',
		'LocalPart' => '(^\\s*(?:(?<NCName1>(?<NCName>[-\\w]+)))\\s*$)',
		'LocationPath' => '(^\\s*(?:(?<RelativeLocationPath1>(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?&RelativeLocationPath))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?&AbsoluteLocationPath)))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\])*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))\\s*|\\s*(?<AbsoluteLocationPath2>(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*$)',
		'MultiplicativeExpr' => '(^\\s*(?:(?<UnaryExpr1>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?&UnaryExpr)\\s*(?:(?:(?&MultiplyOperator)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr)))\\s*(?:(?:(?<MultiplyOperator2>(?<MultiplyOperator>\\*))|div|mod)\\s*(?<UnaryExpr3>(?&UnaryExpr)))?)\\s*$)',
		'MultiplyOperator' => '(^\\s*(?:\\*)\\s*$)',
		'NCName' => '(^\\s*(?:[-\\w]+)\\s*$)',
		'NameTest' => '(^\\s*(?:\\*\\s*|\\s*(?<NCName1>(?<NCName>[-\\w]+))\\s*:\\s*\\*\\s*|\\s*(?<QName2>(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*$)',
		'NodeTest' => '(^\\s*(?:(?<NameTest1>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*|\\s*(?<NodeType2>(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node))\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal3>(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\'))\\s*\\))\\s*$)',
		'NodeType' => '(^\\s*(?:comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*$)',
		'Number' => '(^\\s*(?:(?<Digits1>(?<Digits>[0-9]+))\\s*(?:\\.\\s*(?<Digits2>(?&Digits))?)?\\s*|\\s*\\.\\s*(?<Digits3>(?&Digits)))\\s*$)',
		'Operator' => '(^\\s*(?:(?<OperatorName1>(?<OperatorName>and\\s*|\\s*or\\s*|\\s*mod\\s*|\\s*div))\\s*|\\s*(?<MultiplyOperator2>(?<MultiplyOperator>\\*))\\s*|\\s*//?\\s*|\\s*\\|\\s*|\\s*\\+\\s*|\\s*-\\s*|\\s*=\\s*|\\s*!=\\s*|\\s*<=?\\s*|\\s*>=?)\\s*$)',
		'OperatorName' => '(^\\s*(?:and\\s*|\\s*or\\s*|\\s*mod\\s*|\\s*div)\\s*$)',
		'OrExpr' => '(^\\s*(?:(?<AndExpr1>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?&AndExpr)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?))\\s*(?:or\\s*(?<AndExpr2>(?&AndExpr)))?)\\s*$)',
		'PathExpr' => '(^\\s*(?:(?<FilterExpr1>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?&FilterExpr)\\s*(?://?\\s*(?&RelativeLocationPath))?\\s*|\\s*(?&LocationPath))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*))\\s*(?://?\\s*(?<RelativeLocationPath2>(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*)))?\\s*|\\s*(?<LocationPath3>(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath))))))\\s*$)',
		'Predicate' => '(^\\s*(?:\\[\\s*(?<PredicateExpr1>(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?&PredicateExpr)\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))))\\s*\\])\\s*$)',
		'PredicateExpr' => '(^\\s*(?:(?<Expr1>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))))\\s*$)',
		'Prefix' => '(^\\s*(?:(?<NCName1>(?<NCName>[-\\w]+)))\\s*$)',
		'PrefixedName' => '(^\\s*(?:(?<Prefix1>(?<Prefix>(?<NCName>[-\\w]+)))\\s*:\\s*(?<LocalPart2>(?<LocalPart>(?&NCName))))\\s*$)',
		'PrimaryExpr' => '(^\\s*(?:(?<VariableReference1>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*|\\s*\\(\\s*(?<Expr2>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?&VariableReference)\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?&Number)\\s*|\\s*(?&FunctionCall))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?&NCName)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?&NodeType)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\)\\s*|\\s*(?<Literal3>(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\'))\\s*|\\s*(?<Number4>(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits)))\\s*|\\s*(?<FunctionCall5>(?<FunctionCall>(?<FunctionName>(?!(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\))))\\s*$)',
		'QName' => '(^\\s*(?:(?<PrefixedName1>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName))))\\s*|\\s*(?<UnprefixedName2>(?<UnprefixedName>(?&LocalPart))))\\s*$)',
		'RelationalExpr' => '(^\\s*(?:(?<AdditiveExpr1>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?&AdditiveExpr)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?))\\s*(?:[<>]=?\\s*(?<AdditiveExpr2>(?&AdditiveExpr)))?)\\s*$)',
		'RelativeLocationPath' => '(^\\s*(?:(?<Step1>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?<RelativeLocationPath>(?&Step)\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\])*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?)))\\s*(?://?\\s*(?<Step2>(?&Step))\\s*)*)\\s*$)',
		'Step' => '(^\\s*(?:(?<AxisSpecifier1>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?)))\\s*(?<NodeTest2>(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*\\)))\\s*(?<Predicate3>(?<Predicate>\\[\\s*(?<PredicateExpr>(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?&QName))\\s*|\\s*\\(\\s*(?&Expr)\\s*\\)\\s*|\\s*(?&Literal)\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?&Predicate)*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?&AxisSpecifier)\\s*(?&NodeTest)\\s*(?&Predicate)*\\s*|\\s*(?&AbbreviatedStep))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?)))\\s*\\]))*\\s*|\\s*(?<AbbreviatedStep4>(?<AbbreviatedStep>\\.\\.?)))\\s*$)',
		'UnaryExpr' => '(^\\s*(?:(?<UnionExpr1>(?<UnionExpr>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?&UnaryExpr)\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath)))))\\s*(?:\\|\\s*(?&UnionExpr))?))\\s*|\\s*-\\s*(?<UnaryExpr2>(?<UnaryExpr>(?&UnionExpr)\\s*|\\s*-\\s*(?&UnaryExpr))))\\s*$)',
		'UnionExpr' => '(^\\s*(?:(?<PathExpr1>(?<PathExpr>(?<FilterExpr>(?<PrimaryExpr>(?<VariableReference>\\$\\s*(?<QName>(?<PrefixedName>(?<Prefix>(?&NCName))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart))))\\s*|\\s*\\(\\s*(?<Expr>(?<OrExpr>(?<AndExpr>(?<EqualityExpr>(?<RelationalExpr>(?<AdditiveExpr>(?<MultiplicativeExpr>(?<UnaryExpr>(?&UnionExpr)\\s*|\\s*-\\s*(?&UnaryExpr))\\s*(?:(?:(?<MultiplyOperator>\\*)|div|mod)\\s*(?&UnaryExpr))?)\\s*(?:[-+]\\s*(?&MultiplicativeExpr))?)\\s*(?:[<>]=?\\s*(?&AdditiveExpr))?)\\s*(?:!?=\\s*(?&RelationalExpr))?)\\s*(?:and\\s*(?&AndExpr))?)\\s*(?:or\\s*(?&AndExpr))?))\\s*\\)\\s*|\\s*(?<Literal>"[^"]*"\\s*|\\s*\'[^\']*\')\\s*|\\s*(?<Number>(?<Digits>[0-9]+)\\s*(?:\\.\\s*(?&Digits)?)?\\s*|\\s*\\.\\s*(?&Digits))\\s*|\\s*(?<FunctionCall>(?<FunctionName>(?!(?&NodeType))(?&QName))\\s*\\(\\s*(?:(?<Argument>(?&Expr))\\s*(?:,\\s*(?&Argument)\\s*)*\\s*)?\\s*\\)))\\s*(?<Predicate>\\[\\s*(?<PredicateExpr>(?&Expr))\\s*\\])*)\\s*(?://?\\s*(?<RelativeLocationPath>(?<Step>(?<AxisSpecifier>(?<AxisName>ancestor\\s*|\\s*ancestor-or-self\\s*|\\s*attribute\\s*|\\s*child\\s*|\\s*descendant\\s*|\\s*descendant-or-self\\s*|\\s*following\\s*|\\s*following-sibling\\s*|\\s*namespace\\s*|\\s*parent\\s*|\\s*preceding\\s*|\\s*preceding-sibling\\s*|\\s*self)\\s*::\\s*|\\s*(?<AbbreviatedAxisSpecifier>@?))\\s*(?<NodeTest>(?<NameTest>\\*\\s*|\\s*(?<NCName>[-\\w]+)\\s*:\\s*\\*\\s*|\\s*(?&QName))\\s*|\\s*(?<NodeType>comment\\s*|\\s*text\\s*|\\s*processing-instruction\\s*|\\s*node)\\s*\\(\\s*\\)\\s*|\\s*processing-instruction\\s*\\(\\s*(?&Literal)\\s*\\))\\s*(?&Predicate)*\\s*|\\s*(?<AbbreviatedStep>\\.\\.?))\\s*(?://?\\s*(?&Step)\\s*)*))?\\s*|\\s*(?<LocationPath>(?&RelativeLocationPath)\\s*|\\s*(?<AbsoluteLocationPath>//?\\s*(?&RelativeLocationPath)?\\s*|\\s*(?<AbbreviatedAbsoluteLocationPath>//\\s*(?&RelativeLocationPath))))))\\s*(?:\\|\\s*(?<UnionExpr2>(?<UnionExpr>(?&PathExpr)\\s*(?:\\|\\s*(?&UnionExpr))?)))?)\\s*$)',
		'UnprefixedName' => '(^\\s*(?:(?<LocalPart1>(?<LocalPart>(?<NCName>[-\\w]+))))\\s*$)',
		'VariableReference' => '(^\\s*(?:\\$\\s*(?<QName1>(?<QName>(?<PrefixedName>(?<Prefix>(?<NCName>[-\\w]+))\\s*:\\s*(?<LocalPart>(?&NCName)))\\s*|\\s*(?<UnprefixedName>(?&LocalPart)))))\\s*$)'
	];
}