#!/bin/bash

# catch commits with no message except for the module name
if grep -e "^[a-zA-Z][a-z_A-Z]*: $" $1 > /dev/null;
then
	echo "Aborting commit due to empty commit message."
	exit 1
fi

exit 0