#!/usr/bin/php
<?php

class PHPUnit_Framework_TestCase {}

include __DIR__ . '/../src/autoloader.php';

$test = new s9e\TextFormatter\Tests\ConfigBuilder\TemplateHelperTest;

$php = '';
foreach ($test->getUnsafeTags() as $case)
{
	$php .= "\n\t/**\n\t* @testdox checkUnsafe() identifies " . $case[1] . " as unsafe\n\t*/"
	      . "\n\tpublic function testCheckUnsafe"
	      . sprintf('%08X', crc32(serialize(array_slice($case, 1))))
	      . "()\n\t{\n\t\t\$this->_testUnsafeTags("
	      . "\n\t\t\t" . var_export($case[0], true)
	      . ','
	      . "\n\t\t\t" . var_export($case[1], true)
	      . "\n\t\t);\n\t}\n";
}

$filepath = __DIR__ . '/../tests/ConfigBuilder/TemplateHelperTest.php';
$file = file_get_contents($filepath);

$startComment = '// Start of content generated by ../scripts/' . basename(__FILE__);
$endComment = "\t// End of content generated by ../scripts/" . basename(__FILE__);

$file = substr($file, 0, strpos($file, $startComment) + strlen($startComment))
      . $php
      . substr($file, strpos($file, $endComment));

file_put_contents($filepath, $file);

die("Done.\n");