#!/usr/bin/php
<?php

namespace s9e\TextFormatter\Tests;

class Test {}

$filepath = __DIR__ . '/../tests/Configurator/Helpers/TemplateForensicsTest.php';
include $filepath;

$test = new Configurator\Helpers\TemplateForensicsTest;

$php = '';
foreach ($test->getData() as $k => $case)
{
	$php .= "\n\t/** @testdox " . $case[0] . " */\n\tpublic function test" . sprintf('%08X', crc32(serialize($case))) . '() { $this->runCase(' . $k . "); }\n";
}

$file = file_get_contents($filepath);

$startComment = '// Start of content generated by ../../../../scripts/patchTemplateForensicsTest.php';
$endComment = "\t// End of content generated by ../../../../scripts/patchTemplateForensicsTest.php";

$file = substr($file, 0, strpos($file, $startComment) + strlen($startComment))
      . $php
      . substr($file, strpos($file, $endComment));

file_put_contents($filepath, $file);

die("Done.\n");