#!/bin/sh
TMP=/dev/shm/phpunit.out
ROOT=$(dirname $(dirname $(realpath $0)))

cd "$ROOT"

if [[ -n `git diff --cached --name-only -b | grep \.md` ]]
then
	./scripts/patchExamples.php
	./scripts/generateTOC.php

	git update-index --add "docs/Cookbook/README.md"
fi

if [[ -n `git diff --cached --name-only -b "src" "tests" | grep php` ]]
then
	phpunit --exclude-group none --testdox-text docs/testdox.txt | tee $TMP

	if [[ `tail -n3 $TMP` != *OK* ]]
	then
		exit 1;
	fi

	git update-index --add "docs/testdox.txt"
fi

exit 0