#!/bin/sh
MSG=

for FILEPATH in $(git diff --cached --name-only)
do
	if [[ $FILEPATH != src/* ]] && [[ $FILEPATH != tests/*/* ]];
	then
		continue;
	fi

	MODULE=${FILEPATH#*/}
	MODULE=${MODULE%%/*}

	if [[ `expr match "$MSG" ".*$MODULE"` == 0 ]]
	then
		EXTRA=

		if [[ -z `git diff --cached -b "src/$MODULE" "tests/$MODULE"` ]]
		then
			EXTRA=whitespace
		fi

		MSG="$MSG$MODULE: $EXTRA
"
	fi
done

if [[ -n "$MSG" ]]
then
	MSG="$MSG $(cat $1)"
	echo "$MSG" > $1
fi