#!/bin/sh
DONE=
MSG=`cat $1`
echo -n > $1

echo "$MSG" | while read LINE
do
		if [[ `expr match "$LINE" ".*git add"` -gt 0 ]]
		then
			# stop before we get to the unstaged/untracked files
			exit
		fi

		# will match src/ and tests/
		LEN=`expr match "$LINE" '#\s*[modif]*ed[new file]*:\s*[srct]*/'`

		if [[ $LEN -eq 0 ]]
		then
			continue;
		fi

		MODULE=${LINE:$LEN}
		MODULE=${MODULE%%/*}

		if [[ `expr match "$DONE" ".* $MODULE"` == 0 ]]
		then
			echo "$MODULE:" >> $1
			DONE="$DONE $MODULE"
		fi
done

echo "$MSG" >> $1