#!/bin/sh
MSG=

for FILEPATH in $(git diff --cached --name-only)
do
	if [[ $FILEPATH != src/* ]] && [[ $FILEPATH != tests/*/* ]];
	then
		continue;
	fi

	MODULE=${FILEPATH#*/}
	MODULE=${MODULE%%/*}

	if [[ `expr match "$DONE" ".* $MODULE"` == 0 ]]
	then
		MSG="$MSG$MODULE: 
"
	fi
done

if [[ -n "$MSG" ]]
then
	MSG="$MSG $(cat $1)"
	echo "$MSG" > $1
fi