<?php

namespace s9e\TextFormatter\Tests\ConfigBuilder\Helpers\HTML5;

use s9e\TextFormatter\Tests\Test;
use s9e\TextFormatter\ConfigBuilder\Helpers\HTML5\TagProxy;

/**
* @covers s9e\TextFormatter\ConfigBuilder\Helpers\HTML5\TagProxy
*/
class TagProxyTest extends Test
{
	public function runCase($title, $xslSrc, $rule, $xslTrg)
	{
		$src = new TagProxy(array($xslSrc));
		$trg = new TagProxy(array($xslTrg));

		$methods = array(
			'allowChild'      => array('assertTrue', 'allowsChild'),
			'allowDescendant' => array('assertTrue', 'allowsDescendant'),
			'denyChild'       => array('assertFalse', 'allowsChild'),
			'denyDescendant'  => array('assertFalse', 'allowsDescendant'),
			'closeParent'     => array('assertTrue', 'closesParent')
		);

		list($assert, $method) = $methods[$rule];

		$this->$assert($src->$method($trg));
	}

	// Start of content generated by ../../../../scripts/patchTagProxyTest.php
	/**
	* @testdox <span> does not allow <div> as child
	*/
	public function testD335F821()
	{
		$this->runCase(
			'<span> does not allow <div> as child',
			'<span><xsl:apply-templates/></span>',
			'denyChild',
			'<div><xsl:apply-templates/></div>'
		);
	}

	/**
	* @testdox <span> does not allow <div> as child even with a <span> sibling
	*/
	public function test114C6685()
	{
		$this->runCase(
			'<span> does not allow <div> as child even with a <span> sibling',
			'<span><xsl:apply-templates/></span>',
			'denyChild',
			'<span>xxx</span><div><xsl:apply-templates/></div>'
		);
	}

	/**
	* @testdox <span> and <div> does not allow <span> and <div> as child
	*/
	public function testE416F9F5()
	{
		$this->runCase(
			'<span> and <div> does not allow <span> and <div> as child',
			'<span><xsl:apply-templates/></span><div><xsl:apply-templates/></div>',
			'denyChild',
			'<span/><div/>'
		);
	}

	/**
	* @testdox <li> closes parent <li>
	*/
	public function test93A27904()
	{
		$this->runCase(
			'<li> closes parent <li>',
			'<li/>',
			'closeParent',
			'<li><xsl:apply-templates/></li>'
		);
	}

	/**
	* @testdox <div> closes parent <p>
	*/
	public function test1D189E22()
	{
		$this->runCase(
			'<div> closes parent <p>',
			'<div/>',
			'closeParent',
			'<p><xsl:apply-templates/></p>'
		);
	}

	/**
	* @testdox <p> closes parent <p>
	*/
	public function test94ADCE2C()
	{
		$this->runCase(
			'<p> closes parent <p>',
			'<p/>',
			'closeParent',
			'<p><xsl:apply-templates/></p>'
		);
	}

	/**
	* @testdox <a> denies <a> as descendant
	*/
	public function test176B9DB6()
	{
		$this->runCase(
			'<a> denies <a> as descendant',
			'<a><xsl:apply-templates/></a>',
			'denyDescendant',
			'<a/>'
		);
	}

	/**
	* @testdox <a> allows <img> with no usemap attribute as child
	*/
	public function testFF711579()
	{
		$this->runCase(
			'<a> allows <img> with no usemap attribute as child',
			'<a><xsl:apply-templates/></a>',
			'allowChild',
			'<img/>'
		);
	}

	/**
	* @testdox <a> denies <img usemap="#foo"> as child
	*/
	public function testF13726A8()
	{
		$this->runCase(
			'<a> denies <img usemap="#foo"> as child',
			'<a><xsl:apply-templates/></a>',
			'denyChild',
			'<img usemap="#foo"/>'
		);
	}

	/**
	* @testdox <div><a> allows <div>
	*/
	public function test4640F482()
	{
		$this->runCase(
			'<div><a> allows <div>',
			'<div><a><xsl:apply-templates/></a></div>',
			'allowChild',
			'<div/>'
		);
	}

	/**
	* @testdox <span><a> denies <div>
	*/
	public function test6DBAB744()
	{
		$this->runCase(
			'<span><a> denies <div>',
			'<span><a><xsl:apply-templates/></a></span>',
			'denyChild',
			'<div/>'
		);
	}

	/**
	* @testdox <audio> with no src attribute allows <source>
	*/
	public function testF937B5B2()
	{
		$this->runCase(
			'<audio> with no src attribute allows <source>',
			'<audio><xsl:apply-templates/></audio>',
			'allowChild',
			'<source/>'
		);
	}

	/**
	* @testdox <audio src="..."> denies <source>
	*/
	public function test0D17022C()
	{
		$this->runCase(
			'<audio src="..."> denies <source>',
			'<audio src="{@src}"><xsl:apply-templates/></audio>',
			'denyChild',
			'<source/>'
		);
	}
	// End of content generated by ../../../../scripts/patchTagProxyTest.php

	public function getData()
	{
		return array(
			array(
				'<span> does not allow <div> as child',
				'<span><xsl:apply-templates/></span>',
				'denyChild',
				'<div><xsl:apply-templates/></div>'
			),
			array(
				'<span> does not allow <div> as child even with a <span> sibling',
				'<span><xsl:apply-templates/></span>',
				'denyChild',
				'<span>xxx</span><div><xsl:apply-templates/></div>'
			),
			array(
				'<span> and <div> does not allow <span> and <div> as child',
				'<span><xsl:apply-templates/></span><div><xsl:apply-templates/></div>',
				'denyChild',
				'<span/><div/>'
			),
			array(
				'<li> closes parent <li>',
				'<li/>',
				'closeParent',
				'<li><xsl:apply-templates/></li>'
			),
			array(
				'<div> closes parent <p>',
				'<div/>',
				'closeParent',
				'<p><xsl:apply-templates/></p>'
			),
			array(
				'<p> closes parent <p>',
				'<p/>',
				'closeParent',
				'<p><xsl:apply-templates/></p>'
			),
			array(
				'<a> denies <a> as descendant',
				'<a><xsl:apply-templates/></a>',
				'denyDescendant',
				'<a/>'
			),
			array(
				'<a> allows <img> with no usemap attribute as child',
				'<a><xsl:apply-templates/></a>',
				'allowChild',
				'<img/>'
			),
			array(
				'<a> denies <img usemap="#foo"> as child',
				'<a><xsl:apply-templates/></a>',
				'denyChild',
				'<img usemap="#foo"/>'
			),
			array(
				'<div><a> allows <div>',
				'<div><a><xsl:apply-templates/></a></div>',
				'allowChild',
				'<div/>'
			),
			array(
				'<span><a> denies <div>',
				'<span><a><xsl:apply-templates/></a></span>',
				'denyChild',
				'<div/>'
			),
			array(
				'<audio> with no src attribute allows <source>',
				'<audio><xsl:apply-templates/></audio>',
				'allowChild',
				'<source/>'
			),
			array(
				'<audio src="..."> denies <source>',
				'<audio src="{@src}"><xsl:apply-templates/></audio>',
				'denyChild',
				'<source/>'
			)
		);
	}
}